name = "museumsufer"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[triggers]
crons = ["0 6 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "museumsufer-db"
database_id = "46e70d95-264e-4a5f-bf8e-51f925e47658"

[ai]
binding = "AI"
