/**
 * Display names for hub `source_slug`s. Keys are the slugs each scraper
 * emits; values are the venue's editorial display name. Apps reading from
 * `EVENTS` look up the display name via `displayNameFor(slug)` so the UI
 * shows "Senckenberg Naturmuseum" instead of the slug. Falls back to a
 * titleized slug when an entry is missing — new venues stay usable until
 * a name is curated here.
 *
 * Seeded from a one-time extraction of the per-app config files (see
 * commit history); update entries by hand as venues join or rename. Keep
 * sorted alphabetically by key.
 */
export const VENUE_NAMES: Record<string, string> = {
  "alte-oper": "Alte Oper Frankfurt",
  "andreas-koehs": "Kirchenmusik Andreas Köhs",
  "archaeologisches-museum-frankfurt": "Archäologisches Museum Frankfurt",
  atelierfrankfurt: "Atelierfrankfurt",
  "bad-homburger-schlosskonzerte": "Bad Homburger Schlosskonzerte",
  "bad-soden": "Bad Sodener Kammerkonzerte",
  "bibelhaus-erlebnismuseum": "Bibelhaus ErlebnisMuseum",
  brotfabrik: "Brotfabrik",
  buergeruniversitaet: "Goethe-Uni Bürgeruniversität",
  "caricatura-museum-frankfurt": "Caricatura Museum Frankfurt – Museum für Komische Kunst",
  "denkbar-frankfurt": "Denkbar Frankfurt",
  "deutsches-architekturmuseum": "Deutsches Architekturmuseum (DAM)",
  "deutsches-ledermuseum-of": "Deutsches Ledermuseum Offenbach am Main",
  "deutsches-romantik-museum": "Deutsches Romantik-Museum / Freies Deutsches Hochstift",
  "dff-deutsches-filminstitut-filmmuseum": "DFF – Deutsches Filminstitut & Filmmuseum",
  dialogmuseum: "Dialogmuseum",
  "die-kaes": "Die Käs",
  "die-schmiere": "Die Schmiere",
  "dig-frankfurt": "Deutsch-Israelische Gesellschaft Frankfurt",
  "dommuseum-frankfurt": "Dommuseum Frankfurt",
  "dr-hochs-konservatorium": "Dr. Hoch's Konservatorium",
  "dramatische-buehne": "Die Dramatische Bühne",
  "dresden-frankfurt-dance-company": "Dresden Frankfurt Dance Company",
  "eintracht-frankfurt-museum": "Eintracht Frankfurt Museum",
  "english-theatre-frankfurt": "The English Theatre Frankfurt",
  "ensemble-modern": "Ensemble Modern",
  "evangelische-akademie-frankfurt": "Evangelische Akademie Frankfurt",
  experiminta: "EXPERIMINTA ScienceCenter",
  "fes-hessen": "Friedrich-Ebert-Stiftung Hessen",
  "fgz-streitclub": "FGZ StreitClub",
  "forschungskolleg-humanwissenschaften": "Forschungskolleg Humanwissenschaften (Bad Homburg)",
  "fotografie-forum-frankfurt": "Fotografie Forum Frankfurt",
  "frankfurter-buergerstiftung": "Frankfurter Bürgerstiftung im Holzhausenschlösschen",
  "frankfurter-feldbahnmuseum": "Frankfurter Feldbahnmuseum",
  "frankfurter-goethe-haus": "Frankfurter Goethe-Haus / Freies Deutsches Hochstift",
  "frankfurter-kunstverein": "Frankfurter Kunstverein",
  "galli-theater": "Galli Theater Frankfurt",
  "gallus-theater": "Gallus Theater",
  "geldmuseum-der-deutschen-bundesbank": "Geldmuseum der Deutschen Bundesbank",
  "hambacher-schloss": "Hambacher Schloss",
  "haus-am-dom": "Haus am Dom – Kath. Akademie Rabanus Maurus",
  "haus-der-stadtgeschichte-of": "Haus der Stadtgeschichte Offenbach am Main",
  hfmdk: "Hochschule für Musik und Darstellende Kunst Frankfurt",
  "hindemith-kabinett": "Hindemith Kabinett im Kuhhirtenturm",
  "historisches-museum-frankfurt": "Historisches Museum Frankfurt",
  holzhausenschloesschen: "Holzhausenschlösschen",
  "hr-bigband": "hr-Bigband",
  "hr-sinfonieorchester": "hr-Sinfonieorchester",
  "ikonenmuseum-frankfurt": "Ikonenmuseum Frankfurt",
  "institut-fuer-sozialforschung": "Institut für Sozialforschung Frankfurt",
  "institut-fuer-stadtgeschichte": "Institut für Stadtgeschichte",
  "internationales-theater": "Internationales Theater Frankfurt",
  "jazz-frankfurt": "Jazz in Frankfurt",
  "jazz-palmengarten": "Jazz im Palmengarten",
  "juedische-gemeinde-frankfurt": "Jüdische Gemeinde Frankfurt",
  "juedisches-museum-frankfurt": "Jüdisches Museum Frankfurt",
  "juedisches-museum-museum-judengasse-frankfurt": "Jüdisches Museum / Museum Judengasse Frankfurt",
  "junges-museum-frankfurt": "Junges Museum Frankfurt",
  "kellertheater-frankfurt": "Kellertheater Frankfurt",
  "kirchenmusik-dreikoenig": "Kirchenmusik Dreikönigsgemeinde",
  "klingspor-museum-of": "Klingspor Museum – Offenbach am Main",
  "komoedie-frankfurt": "Die Komödie Frankfurt",
  "kronberg-academy": "Kronberg Academy / Casals Forum",
  "kulturnetz-landau": "Kulturnetz Landau",
  "kunststiftung-dz-bank": "Kunststiftung DZ BANK",
  "landau-de": "Stadt Landau in der Pfalz",
  landungsbruecken: "Landungsbrücken Frankfurt",
  "liebieghaus-skulpturensammlung": "Liebieghaus Skulpturensammlung",
  "literaturhaus-frankfurt": "Literaturhaus Frankfurt",
  "momem-museum-of-modern-electronic-music": "MOMEM – Museum of Modern Electronic Music",
  mousonturm: "Künstler*innenhaus Mousonturm",
  "museum-angewandte-kunst": "Museum Angewandte Kunst",
  "museum-fuer-kommunikation-frankfurt": "Museum für Kommunikation Frankfurt",
  "museum-giersch-der-goethe-universitaet": "MGGU – Museum Giersch der Goethe-Universität",
  "museum-mmk-museum-mmk-fuer-moderne-kunst": "MUSEUM MMK – MUSEUM MMK FÜR MODERNE KUNST",
  "museum-sinclair-haus-bad-homburg": "Museum Sinclair-Haus Bad Homburg",
  "musikschule-frankfurt": "Städtische Musikschule Frankfurt",
  "naxos-hallenkonzerte": "Naxos Hallenkonzerte",
  "neues-theater-hoechst": "Neues Theater Höchst",
  "normative-orders": "Forschungsverbund Normative Ordnungen",
  "openbooks-frankfurt": "OPEN BOOKS Frankfurt",
  "oper-frankfurt": "Oper Frankfurt",
  "oper-frankfurt-konzerte": "Oper Frankfurt – Konzerte & Liederabende",
  "papageno-musiktheater": "Papageno Musiktheater",
  "pfalz-de": "Pfalz Tourismus",
  "polytechnische-gesellschaft": "Polytechnische Gesellschaft Frankfurt",
  portikus: "Portikus",
  "porzellan-museum-frankfurt": "Porzellan Museum Frankfurt",
  "rheingau-musikfestival": "Rheingau Musik Festival",
  "rls-hessen": "Rosa-Luxemburg-Stiftung Hessen",
  roemerberggespraeche: "Römerberggespräche Frankfurt",
  romanfabrik: "Romanfabrik Frankfurt",
  "rptu-campuskultur": "RPTU Landau – Campuskultur",
  "schauspiel-frankfurt": "Schauspiel Frankfurt",
  "schirn-in-bockenheim": "Schirn in Bockenheim",
  "schirn-kunsthalle-frankfurt": "Schirn Kunsthalle Frankfurt",
  "senckenberg-naturmuseum": "Senckenberg Naturmuseum",
  "sigmund-freud-institut": "Sigmund-Freud-Institut Frankfurt",
  "st-katharinen": "Kantorei St. Katharinen",
  "stadtbuecherei-frankfurt": "Stadtbücherei Frankfurt",
  "staedel-museum": "Städel Museum",
  "stalburg-theater": "Stalburg Theater",
  "stoltze-museum": "Stoltze-Museum der Frankfurter Sparkasse",
  "struwwelpeter-museum": "Struwwelpeter Museum",
  suew: "Südliche Weinstraße",
  "theater-alte-bruecke": "Theater Alte Brücke",
  "theater-lempenfieber": "Theater Lempenfieber",
  "theater-willy-praml": "Theater Willy Praml",
  "theaterhaus-frankfurt": "Theaterhaus Frankfurt",
  "tigerpalast-variete": "Tigerpalast Varieté",
  "tower-mmk-museum-mmk-fuer-moderne-kunst": "Tower MMK – Museum MMK für Moderne Kunst",
  "verkehrsmuseum-frankfurt": "Verkehrsmuseum Frankfurt am Main",
  "volksbuehne-frankfurt": "Volksbühne im Großen Hirschgraben",
  waggong: "Waggong e.V. — Kulturwerkstatt Germaniastraße",
  "weltkulturen-museum": "Weltkulturen Museum",
  "wollheim-memorial-frankfurt": "Wollheim Memorial",
  "zollamt-mmk-museum-mmk-fuer-moderne-kunst": "Zollamt MMK – Museum MMK für Moderne Kunst",
};

/** Look up a venue's display name. Falls back to a titleized slug when
 *  no curated entry exists, so brand-new venues remain usable. */
export function displayNameFor(slug: string): string {
  return VENUE_NAMES[slug] ?? titleize(slug);
}

function titleize(slug: string): string {
  return slug
    .split("-")
    .map((w) => (w.length > 0 ? w[0].toUpperCase() + w.slice(1) : w))
    .join(" ");
}
