-- Scraped data moved out of D1 and into a bundled module
-- (src/scrape-data.ts), regenerated by .github/workflows/scrape.yml. The
-- worker no longer reads `theaters`, `shows`, or `performances` — drop
-- them. The `feedback` and `translations` tables stay (user-submitted
-- and DeepL cache, respectively).

DROP TABLE IF EXISTS performances;
DROP TABLE IF EXISTS shows;
DROP TABLE IF EXISTS theaters;
