#!/usr/bin/env bun
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { bundleSection } from "@museumsufer/core/bundle-writer";
import { todayIso } from "@museumsufer/core/date";
import { fnv1aInt } from "@museumsufer/core/hash";
import { type CanonicalEvent, displayNameFor, EVENTS, FRANKFURT_BBOX, inBbox } from "@museumsufer/event-hub";
import { SOURCES } from "../src/source-config";
import type { Category, LehrhausEvent, LehrhausSource, ScrapeData } from "../src/types";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const today = todayIso();

await main();

async function main(): Promise<void> {
  const sourcesBySlug = new Map(SOURCES.map((s) => [s.slug, s]));
  const events: LehrhausEvent[] = [];
  const orphanUrls = new Map<string, string>();

  for (const ev of EVENTS) {
    if (ev.date < today) continue;
    if (!inBbox(ev.lat, ev.lon, FRANKFURT_BBOX)) continue;
    const category = pickCategory(ev);
    if (!category) continue;

    if (!sourcesBySlug.has(ev.source_slug) && !orphanUrls.has(ev.source_slug) && ev.detail_url) {
      orphanUrls.set(ev.source_slug, originOf(ev.detail_url));
    }

    events.push({
      id: fnv1aInt(`${ev.source_slug}|${ev.title}|${ev.date}|${ev.time ?? ""}`),
      source_slug: ev.source_slug,
      source_name: sourcesBySlug.get(ev.source_slug)?.name ?? displayNameFor(ev.source_slug),
      title: ev.title,
      date: ev.date,
      time: ev.time,
      end_time: ev.end_time,
      description: ev.description,
      detail_url: ev.detail_url,
      ticket_url: ev.ticket_url,
      category,
      language: ev.language,
      image_url: ev.image_url,
    });
  }

  // Deduplicate by id (same talk picked up from multiple labels).
  const seen = new Set<number>();
  const unique: LehrhausEvent[] = [];
  for (const e of events) {
    if (seen.has(e.id)) continue;
    seen.add(e.id);
    unique.push(e);
  }
  unique.sort(
    (a, b) =>
      a.date.localeCompare(b.date) || (a.time ?? "").localeCompare(b.time ?? "") || a.title.localeCompare(b.title),
  );

  const sources = augmentSources(SOURCES, orphanUrls);
  log(`${unique.length} talks across ${sources.length} sources (${orphanUrls.size} synthesised)`);

  const data: ScrapeData = { sources, events: unique };
  await writeFile(resolve(root, "src/scrape-data.ts"), generateModule(data), "utf8");
  log(`wrote src/scrape-data.ts — ${unique.length} events`);
}

function augmentSources(curated: LehrhausSource[], orphanUrls: Map<string, string>): LehrhausSource[] {
  const known = new Set(curated.map((s) => s.slug));
  const extras: LehrhausSource[] = [];
  for (const [slug, url] of orphanUrls) {
    if (known.has(slug)) continue;
    extras.push({ slug, name: displayNameFor(slug), url });
  }
  extras.sort((a, b) => a.slug.localeCompare(b.slug));
  return [...curated, ...extras];
}

function originOf(url: string): string {
  try {
    return new URL(url).origin;
  } catch {
    return "";
  }
}

function pickCategory(ev: CanonicalEvent): Category | null {
  for (const l of ev.labels) {
    if (l.label === "talk:vortrag") return "Vortrag";
    if (l.label === "talk:diskussion") return "Diskussion";
    if (l.label === "talk:lesung") return "Lesung";
  }
  return null;
}

function generateModule(data: ScrapeData): string {
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.
import type { ScrapeData } from "./types";

export const SCRAPE_DATA: ScrapeData = {
${bundleSection("sources", data.sources as unknown as Record<string, unknown>[])}
${bundleSection("events", data.events as unknown as Record<string, unknown>[])}
};
`;
}

function log(msg: string): void {
  process.stderr.write(`[lehrhaus] ${msg}\n`);
}
