#!/usr/bin/env bun
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { bundleSection } from "@museumsufer/core/bundle-writer";
import { todayIso } from "@museumsufer/core/date";
import { fnv1aInt } from "@museumsufer/core/hash";
import { type CanonicalEvent, displayNameFor, EVENTS, MUSEUM_SLUGS, THEATER_SLUGS } from "@museumsufer/event-hub";
import { SOURCES } from "../src/source-config";
import type { Category, LehrhausEvent, LehrhausSource, ScrapeData } from "../src/types";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const today = todayIso();

await main();

async function main(): Promise<void> {
  const sourcesBySlug = new Map(SOURCES.map((s) => [s.slug, s]));
  const directSlugs = new Set(
    SOURCES.filter((s) => s.slug !== "frankfurt-museums" && s.slug !== "frankfurt-theaters").map((s) => s.slug),
  );

  const events: LehrhausEvent[] = [];
  const counts = { direct: 0, museums: 0, theaters: 0, other: 0 };
  const orphanUrls = new Map<string, string>();

  for (const ev of EVENTS) {
    if (ev.date < today) continue;
    const category = pickCategory(ev);
    if (!category) continue;

    const sourceSlug = placeEvent(ev, directSlugs);
    if (sourceSlug === "frankfurt-museums") counts.museums++;
    else if (sourceSlug === "frankfurt-theaters") counts.theaters++;
    else if (directSlugs.has(sourceSlug)) counts.direct++;
    else {
      counts.other++;
      if (!orphanUrls.has(sourceSlug) && ev.detail_url) orphanUrls.set(sourceSlug, originOf(ev.detail_url));
    }

    const sourceName =
      sourceSlug === ev.source_slug
        ? (sourcesBySlug.get(sourceSlug)?.name ?? displayNameFor(ev.source_slug))
        : displayNameFor(ev.source_slug);

    events.push({
      id: fnv1aInt(`${sourceSlug}|${ev.title}|${ev.date}|${ev.time ?? ""}`),
      source_slug: sourceSlug,
      source_name: sourceName,
      title: ev.title,
      date: ev.date,
      time: ev.time,
      end_time: ev.end_time,
      description: ev.description,
      detail_url: ev.detail_url,
      ticket_url: ev.ticket_url,
      category,
      language: ev.language,
      image_url: ev.image_url,
    });
  }

  // Deduplicate by id (same talk picked up from multiple labels).
  const seen = new Set<number>();
  const unique: LehrhausEvent[] = [];
  for (const e of events) {
    if (seen.has(e.id)) continue;
    seen.add(e.id);
    unique.push(e);
  }
  unique.sort(
    (a, b) =>
      a.date.localeCompare(b.date) || (a.time ?? "").localeCompare(b.time ?? "") || a.title.localeCompare(b.title),
  );

  const sources = augmentSources(SOURCES, orphanUrls);
  log(
    `direct: ${counts.direct}, museums: ${counts.museums}, theaters: ${counts.theaters}, other: ${counts.other} (${orphanUrls.size} extra sources) → ${unique.length} unique events`,
  );

  const data: ScrapeData = { sources, events: unique };
  await writeFile(resolve(root, "src/scrape-data.ts"), generateModule(data), "utf8");
  log(`wrote src/scrape-data.ts — ${unique.length} events`);
}

function augmentSources(curated: LehrhausSource[], orphanUrls: Map<string, string>): LehrhausSource[] {
  const known = new Set(curated.map((s) => s.slug));
  const extras: LehrhausSource[] = [];
  for (const [slug, url] of orphanUrls) {
    if (known.has(slug)) continue;
    extras.push({ slug, name: displayNameFor(slug), url });
  }
  extras.sort((a, b) => a.slug.localeCompare(b.slug));
  return [...curated, ...extras];
}

function originOf(url: string): string {
  try {
    return new URL(url).origin;
  } catch {
    return "";
  }
}

function pickCategory(ev: CanonicalEvent): Category | null {
  for (const l of ev.labels) {
    if (l.label === "talk:vortrag") return "Vortrag";
    if (l.label === "talk:diskussion") return "Diskussion";
    if (l.label === "talk:lesung") return "Lesung";
  }
  return null;
}

/**
 * Decide which `LehrhausSource` slug a hub event belongs to. Direct mappings
 * win for the 20 institution-specific sources; museum and theater venues
 * roll up under `frankfurt-museums` / `frankfurt-theaters`. Anything else
 * (e.g. brotfabrik's occasional talks) keeps its own slug — a synthesized
 * source row gets added so the UI can render it.
 */
function placeEvent(ev: CanonicalEvent, directSlugs: Set<string>): string {
  if (directSlugs.has(ev.source_slug)) return ev.source_slug;
  if (MUSEUM_SLUGS.has(ev.source_slug)) return "frankfurt-museums";
  if (THEATER_SLUGS.has(ev.source_slug)) return "frankfurt-theaters";
  return ev.source_slug;
}

function generateModule(data: ScrapeData): string {
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.
import type { ScrapeData } from "./types";

export const SCRAPE_DATA: ScrapeData = {
${bundleSection("sources", data.sources as unknown as Record<string, unknown>[])}
${bundleSection("events", data.events as unknown as Record<string, unknown>[])}
};
`;
}

function log(msg: string): void {
  process.stderr.write(`[lehrhaus] ${msg}\n`);
}
