#!/usr/bin/env bun
/**
 * Walks every venue config, dispatches the matching scraper via a
 * concurrency-limited queue, applies genre heuristics, computes stable
 * FNV-1a IDs, and writes the aggregated result to src/scrape-data.ts.
 *
 * Deterministic output: stable IDs, sorted arrays, sorted object keys.
 * Two runs on identical upstream data produce byte-identical output.
 */
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { bundleSection } from "@museumsufer/core/bundle-writer";
import { todayIso } from "@museumsufer/core/date";
import { fnv1aInt } from "@museumsufer/core/hash";
import PQueue from "p-queue";
import { VENUES, type VenueConfig } from "../src/concert-config";
import { dedupEvents } from "../src/dedup";
import { classify } from "../src/genre-heuristics";
import { runScraper } from "../src/scrape-runner";
import type { Event, ScrapeData, ScrapedEvent } from "../src/types";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const today = todayIso();
const CONCURRENCY = 5;

await main();

async function main(): Promise<void> {
  const eventsById = new Map<number, Event>();
  let okCount = 0;
  let failCount = 0;

  const queue = new PQueue({ concurrency: CONCURRENCY });
  for (const venue of VENUES) {
    queue.add(async () => {
      try {
        const result = await runScraper(venue.scraper);
        ingest(venue, result.events, eventsById);
        log(`${venue.slug.padEnd(36, " ")} ok — ${result.events.length} events`);
        okCount++;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        log(`${venue.slug.padEnd(36, " ")} FAIL — ${msg}`);
        failCount++;
      }
    });
  }
  await queue.onIdle();

  const data: ScrapeData = buildScrapeData(eventsById);
  await writeFile(resolve(root, "src/scrape-data.ts"), generateModule(data), "utf8");

  log(`${okCount}/${VENUES.length} ok, ${failCount} failed — wrote src/scrape-data.ts (${data.events.length} events)`);
  if (failCount > 0 && okCount === 0) process.exit(1);
}

function ingest(venue: VenueConfig, scraped: ScrapedEvent[], eventsById: Map<number, Event>): void {
  for (const s of scraped) {
    if (s.date < today) continue;
    const genre = s.genre ?? classify(s.title, s.subtitle, s.description, venue.default_genre);
    const canonicalTitle = s.title.toLowerCase().replace(/[^a-z0-9]+/g, "");
    const canonicalTitleHash = fnv1aInt(canonicalTitle);
    const id = fnv1aInt(`${venue.slug}|${s.date}|${s.time ?? ""}|${s.venue_room ?? ""}|${canonicalTitleHash}`);
    if (eventsById.has(id)) continue;
    eventsById.set(id, {
      id,
      venue_slug: venue.slug,
      slug: s.slug,
      title: s.title,
      subtitle: s.subtitle ?? undefined,
      description: s.description ?? undefined,
      date: s.date,
      time: s.time ?? undefined,
      end_time: s.end_time ?? undefined,
      genre,
      image_url: s.image_url ?? undefined,
      detail_url: s.detail_url ?? undefined,
      ticket_url: s.ticket_url ?? undefined,
      price_min: s.price_min ?? undefined,
      price_max: s.price_max ?? undefined,
      venue_room: s.venue_room ?? undefined,
      performers: s.performers ?? undefined,
    });
  }
}

function buildScrapeData(eventsById: Map<number, Event>): ScrapeData {
  const deduped = dedupEvents([...eventsById.values()]);
  const events = deduped.sort(
    (a, b) =>
      a.date.localeCompare(b.date) ||
      (a.time ?? "").localeCompare(b.time ?? "") ||
      a.venue_slug.localeCompare(b.venue_slug) ||
      a.title.localeCompare(b.title),
  );
  return { events };
}

function generateModule(data: ScrapeData): string {
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.
import type { ScrapeData } from "./types";

export const SCRAPE_DATA: ScrapeData = {
${bundleSection("events", data.events)}
};
`;
}

function log(msg: string): void {
  process.stderr.write(`[scrape] ${msg}\n`);
}
