#!/usr/bin/env bun
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { bundleSection } from "@museumsufer/core/bundle-writer";
import { todayIso } from "@museumsufer/core/date";
import { fnv1aInt } from "@museumsufer/core/hash";
import type { CanonicalEvent } from "@museumsufer/event-hub";
import { displayNameFor, EVENTS, FRANKFURT_BBOX, inBbox } from "@museumsufer/event-hub";
import { CURATED_VENUES, type VenueConfig } from "../src/concert-config";
import { dedupEvents } from "../src/dedup";
import { type Event, GENRES, type Genre, type ScrapeData } from "../src/types";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const today = todayIso();

await main();

async function main(): Promise<void> {
  const curatedBySlug = new Map(CURATED_VENUES.map((v) => [v.slug, v]));
  const eventsById = new Map<number, Event>();
  const counts = new Map<string, number>();
  const orphanGenres = new Map<string, Map<Genre, number>>();
  const orphanUrls = new Map<string, string>();

  for (const ev of EVENTS) {
    if (ev.date < today) continue;
    if (!inBbox(ev.lat, ev.lon, FRANKFURT_BBOX)) continue;
    const genre = pickGenre(ev);
    if (!genre) continue;

    const canonicalTitleHash = fnv1aInt(ev.title.toLowerCase().replace(/[^a-z0-9]+/g, ""));
    const id = fnv1aInt(`${ev.source_slug}|${ev.date}|${ev.time ?? ""}|${ev.venue_room ?? ""}|${canonicalTitleHash}`);
    if (eventsById.has(id)) continue;
    eventsById.set(id, {
      id,
      venue_slug: ev.source_slug,
      slug: ev.source_event_id,
      title: ev.title,
      subtitle: ev.subtitle,
      description: ev.description,
      date: ev.date,
      time: ev.time,
      end_time: ev.end_time,
      genre,
      image_url: ev.image_url,
      detail_url: ev.detail_url,
      ticket_url: ev.ticket_url,
      price_min: ev.price_min,
      price_max: ev.price_max,
      venue_room: ev.venue_room,
      performers: ev.performers,
    });
    counts.set(ev.source_slug, (counts.get(ev.source_slug) ?? 0) + 1);
    if (!curatedBySlug.has(ev.source_slug)) {
      const tally = orphanGenres.get(ev.source_slug) ?? new Map<Genre, number>();
      tally.set(genre, (tally.get(genre) ?? 0) + 1);
      orphanGenres.set(ev.source_slug, tally);
      if (!orphanUrls.has(ev.source_slug) && ev.detail_url) {
        orphanUrls.set(ev.source_slug, originOf(ev.detail_url));
      }
    }
  }

  const synthesized = synthesizeVenues(orphanGenres, orphanUrls);
  const deduped = dedupEvents([...eventsById.values()]);
  deduped.sort(
    (a, b) =>
      a.date.localeCompare(b.date) ||
      (a.time ?? "").localeCompare(b.time ?? "") ||
      a.venue_slug.localeCompare(b.venue_slug) ||
      a.title.localeCompare(b.title),
  );

  const data: ScrapeData = { events: deduped };
  await writeFile(resolve(root, "src/scrape-data.ts"), generateModule(data), "utf8");
  await writeFile(resolve(root, "src/synthesized-venues.ts"), generateVenuesModule(synthesized), "utf8");

  const seenCount = [...counts.entries()].sort((a, b) => b[1] - a[1]);
  for (const [slug, n] of seenCount) log(`  ${slug.padEnd(36, " ")} ${n}`);
  log(`wrote ${deduped.length} events from ${counts.size} venues (${synthesized.length} synthesised)`);
}

function synthesizeVenues(
  orphanGenres: Map<string, Map<Genre, number>>,
  orphanUrls: Map<string, string>,
): VenueConfig[] {
  const coordsBySlug = new Map<string, { lat: number; lon: number }>();
  for (const ev of EVENTS) {
    if (orphanGenres.has(ev.source_slug) && !coordsBySlug.has(ev.source_slug)) {
      coordsBySlug.set(ev.source_slug, { lat: ev.lat, lon: ev.lon });
    }
  }
  const out: VenueConfig[] = [];
  for (const [slug, genres] of orphanGenres) {
    const coords = coordsBySlug.get(slug);
    if (!coords) continue;
    const defaultGenre = [...genres.entries()].sort((a, b) => b[1] - a[1])[0][0];
    out.push({
      slug,
      name: displayNameFor(slug),
      address: "",
      lat: coords.lat,
      lon: coords.lon,
      city: "frankfurt",
      website_url: orphanUrls.get(slug) ?? "",
      default_genre: defaultGenre,
    });
  }
  return out.sort((a, b) => a.slug.localeCompare(b.slug));
}

function originOf(url: string): string {
  try {
    return new URL(url).origin;
  } catch {
    return "";
  }
}

function generateVenuesModule(venues: VenueConfig[]): string {
  const entries = venues
    .map(
      (v) =>
        `  {
    slug: ${JSON.stringify(v.slug)},
    name: ${JSON.stringify(v.name)},
    address: ${JSON.stringify(v.address)},
    lat: ${v.lat},
    lon: ${v.lon},
    city: ${JSON.stringify(v.city)},
    website_url: ${JSON.stringify(v.website_url)},
    default_genre: ${JSON.stringify(v.default_genre)},
  },`,
    )
    .join("\n");
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.
import type { VenueConfig } from "./concert-config";

export const SYNTHESIZED_VENUES: VenueConfig[] = [
${entries}
];
`;
}

function pickGenre(ev: CanonicalEvent): Genre | null {
  let best: { genre: Genre; confidence: number } | null = null;
  for (const l of ev.labels) {
    if (!l.label.startsWith("music:")) continue;
    const tail = l.label.slice("music:".length);
    if (!(GENRES as readonly string[]).includes(tail)) continue;
    const genre = tail as Genre;
    if (!best || l.confidence > best.confidence) best = { genre, confidence: l.confidence };
  }
  return best?.genre ?? null;
}

function generateModule(data: ScrapeData): string {
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.
import type { ScrapeData } from "./types";

export const SCRAPE_DATA: ScrapeData = {
${bundleSection("events", data.events)}
};
`;
}

function log(msg: string): void {
  process.stderr.write(`[konzert-haus] ${msg}\n`);
}
