#!/usr/bin/env bun
/**
 * Derives konzert-haus's `src/scrape-data.ts` from the central event hub.
 * Filters `EVENTS` to entries whose `source_slug` is a konzert-haus venue
 * and that carry a `music:*` label, then maps each canonical event onto
 * the konzert-haus `Event` shape. Per-venue scraping moved into
 * `packages/scrapers/src/venues/`; this script is now a pure transform.
 */
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { bundleSection } from "@museumsufer/core/bundle-writer";
import { todayIso } from "@museumsufer/core/date";
import { fnv1aInt } from "@museumsufer/core/hash";
import { type CanonicalEvent, EVENTS } from "@museumsufer/event-hub";
import { VENUES } from "../src/concert-config";
import { dedupEvents } from "../src/dedup";
import { type Event, GENRES, type Genre, parseGenre, type ScrapeData } from "../src/types";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const today = todayIso();

await main();

async function main(): Promise<void> {
  const venueSlugs = new Set(VENUES.map((v) => v.slug));
  const defaultGenreBySlug = new Map(VENUES.map((v) => [v.slug, v.default_genre]));
  const eventsById = new Map<number, Event>();
  const counts = new Map<string, number>();

  for (const ev of EVENTS) {
    if (ev.date < today) continue;
    if (!venueSlugs.has(ev.source_slug)) continue;
    const genre = pickGenre(ev) ?? defaultGenreBySlug.get(ev.source_slug);
    if (!genre) continue;

    const canonicalTitleHash = fnv1aInt(ev.title.toLowerCase().replace(/[^a-z0-9]+/g, ""));
    const id = fnv1aInt(`${ev.source_slug}|${ev.date}|${ev.time ?? ""}|${ev.venue_room ?? ""}|${canonicalTitleHash}`);
    if (eventsById.has(id)) continue;
    eventsById.set(id, {
      id,
      venue_slug: ev.source_slug,
      slug: ev.source_event_id,
      title: ev.title,
      subtitle: ev.subtitle,
      description: ev.description,
      date: ev.date,
      time: ev.time,
      end_time: ev.end_time,
      genre,
      image_url: ev.image_url,
      detail_url: ev.detail_url,
      ticket_url: ev.ticket_url,
      price_min: ev.price_min,
      price_max: ev.price_max,
      venue_room: ev.venue_room,
      performers: ev.performers,
    });
    counts.set(ev.source_slug, (counts.get(ev.source_slug) ?? 0) + 1);
  }

  const deduped = dedupEvents([...eventsById.values()]);
  deduped.sort(
    (a, b) =>
      a.date.localeCompare(b.date) ||
      (a.time ?? "").localeCompare(b.time ?? "") ||
      a.venue_slug.localeCompare(b.venue_slug) ||
      a.title.localeCompare(b.title),
  );

  const data: ScrapeData = { events: deduped };
  await writeFile(resolve(root, "src/scrape-data.ts"), generateModule(data), "utf8");

  const seenCount = [...counts.entries()].sort((a, b) => b[1] - a[1]);
  for (const [slug, n] of seenCount) log(`  ${slug.padEnd(36, " ")} ${n}`);
  log(`wrote src/scrape-data.ts — ${deduped.length} events from ${counts.size} venues`);
}

/** Read the music genre off the highest-confidence `music:<genre>` label,
 *  if any. Each hub event carries one music:* label per scrape-time pass. */
function pickGenre(ev: CanonicalEvent): Genre | null {
  let best: { genre: Genre; confidence: number } | null = null;
  for (const l of ev.labels) {
    if (!l.label.startsWith("music:")) continue;
    const tail = l.label.slice("music:".length);
    if (!(GENRES as readonly string[]).includes(tail)) continue;
    const genre = tail as Genre;
    if (!best || l.confidence > best.confidence) best = { genre, confidence: l.confidence };
  }
  return best?.genre ?? null;
}

void parseGenre;

function generateModule(data: ScrapeData): string {
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.
import type { ScrapeData } from "./types";

export const SCRAPE_DATA: ScrapeData = {
${bundleSection("events", data.events)}
};
`;
}

function log(msg: string): void {
  process.stderr.write(`[konzert-haus] ${msg}\n`);
}
