#!/usr/bin/env bun
/**
 * Hand-run enrichment: (re)build the committed PDF-programme cache via the AI
 * proxy. NOT part of `scrape()` or CI — an LLM call is non-deterministic and
 * network-bound (see AGENTS.md "LLM access" + the determinism rule), so it runs
 * by hand, its output (`src/data/pdf-events-cache.ts`) is reviewed and committed,
 * and the venue scrapers consume only that committed file.
 *
 * Idempotent: each venue's PDF is fetched + hashed first; the LLM is invoked only
 * when the hash (or schema `version`) differs from the committed entry.
 *
 *   export AI_PROXY_URL=$(gh variable get AI_PROXY_URL)
 *   bun packages/scrapers/scripts/refresh-pdf-cache.ts            # top up changed PDFs
 *   bun packages/scrapers/scripts/refresh-pdf-cache.ts --force    # re-extract all
 *   bun packages/scrapers/scripts/refresh-pdf-cache.ts --dry-run  # don't write
 */
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { PDF_EVENTS_CACHE } from "../src/data/pdf-events-cache";
import { eventsFromText, fetchPdfText, type ProgrammeEventsCache } from "../src/programme-events";

const UA = "museumsufer pdf-cache builder / contact: jonas@bgdlabs.com";

interface PdfVenue {
  /** Cache key; also the scraper's lookup tag. */
  tag: string;
  /** Bump to invalidate this venue's cached extraction after a prompt change. */
  version: number;
  /** Venue-specific hint appended to the extraction system prompt. */
  prompt?: string;
  /** Resolve the current PDF URL (programmes move filename each edition). */
  discover(): Promise<string>;
}

const MAINAEPPELHAUS_PROGRAM =
  "https://www.mainaeppelhauslohrberg.de/index.php/lohrberg-erleben/veranstaltungskalender.html";

const VENUES: PdfVenue[] = [
  {
    tag: "mainaeppelhaus-lohrberg",
    version: 3,
    prompt: "Das Programm stammt vom MainÄppelHaus Lohrberg (Streuobstzentrum auf dem Lohrberg, Frankfurt).",
    async discover() {
      const res = await fetch(MAINAEPPELHAUS_PROGRAM, { headers: { "User-Agent": UA }, signal: AbortSignal.timeout(30_000) });
      if (!res.ok) throw new Error(`mainaeppelhaus calendar ${res.status}`);
      const href = (await res.text()).match(/\/images\/dokumente\/[^"']*\.pdf/i)?.[0];
      if (!href) throw new Error("mainaeppelhaus: PDF link not found on calendar page");
      return new URL(href, MAINAEPPELHAUS_PROGRAM).href;
    },
  },
];

const here = dirname(fileURLToPath(import.meta.url));

await main();

async function main(): Promise<void> {
  const aiProxyUrl = process.env.AI_PROXY_URL;
  if (!aiProxyUrl) {
    err("AI_PROXY_URL not set — run: export AI_PROXY_URL=$(gh variable get AI_PROXY_URL)");
    process.exit(1);
  }
  const model = process.env.AI_PROXY_MODEL;
  const force = process.argv.includes("--force");
  const dryRun = process.argv.includes("--dry-run");

  const cache: ProgrammeEventsCache = { ...PDF_EVENTS_CACHE };
  let changed = false;

  for (const v of VENUES) {
    try {
      const url = await v.discover();
      const { text, hash } = await fetchPdfText(url);
      const existing = cache[v.tag];
      if (!force && existing && existing.hash === hash && existing.version === v.version) {
        err(`${v.tag}: unchanged (${existing.events.length} events) — skip`);
        continue;
      }
      err(`${v.tag}: extracting via ${new URL(aiProxyUrl).host} (${model ?? "gemini-2.5-flash"}) …`);
      const events = await eventsFromText(text, { aiProxyUrl, model, prompt: v.prompt });
      cache[v.tag] = { hash, version: v.version, events };
      changed = true;
      err(`${v.tag}: ${events.length} events extracted`);
    } catch (e) {
      err(`${v.tag}: FAILED — ${(e as Error).message}`);
    }
  }

  if (!changed) {
    err("no changes");
    return;
  }
  if (dryRun) {
    err("--dry-run: not writing");
    return;
  }
  await writeFile(resolve(here, "../src/data/pdf-events-cache.ts"), generateModule(cache), "utf8");
  err(`wrote src/data/pdf-events-cache.ts — ${Object.keys(cache).length} venue(s)`);
}

/** Deterministic module: top-level keys sorted; each entry a single JSON line
 *  (entry + event field order is fixed by the helper), so reruns are byte-stable. */
function generateModule(cache: ProgrammeEventsCache): string {
  const lines = Object.keys(cache)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(cache[k])},`);
  return `// Auto-generated by scripts/refresh-pdf-cache.ts — do not edit by hand.
import type { ProgrammeEventsCache } from "../programme-events";

export const PDF_EVENTS_CACHE: ProgrammeEventsCache = {
${lines.join("\n")}
};
`;
}

function err(msg: string): void {
  process.stderr.write(`[pdf-cache] ${msg}\n`);
}
