#!/usr/bin/env bun
/**
 * Hand-run enrichment: (re)build the committed HTML-page event cache via the AI
 * proxy. The HTML sibling of `refresh-pdf-cache.ts`. NOT part of `scrape()` or
 * CI — an LLM call is non-deterministic and network-bound (see AGENTS.md "LLM
 * access" + the determinism rule), so it runs by hand, its output
 * (`src/data/html-events-cache.ts`) is reviewed and committed, and the venue
 * scrapers consume only that committed file.
 *
 * Idempotent: each page's plain text is fetched + hashed first; the LLM is
 * invoked only when the hash (or schema `version`) differs from the committed entry.
 *
 *   export AI_PROXY_URL=$(gh variable get AI_PROXY_URL)
 *   bun packages/scrapers/scripts/refresh-html-cache.ts            # top up changed pages
 *   bun packages/scrapers/scripts/refresh-html-cache.ts --force    # re-extract all
 *   bun packages/scrapers/scripts/refresh-html-cache.ts --dry-run  # don't write
 */
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { HTML_EVENTS_CACHE } from "../src/data/html-events-cache";
import { eventsFromText, fetchHtmlText, type ProgrammeEventsCache } from "../src/programme-events";

interface HtmlVenue {
  /** Cache key; also the scraper's lookup tag. */
  tag: string;
  /** Bump to invalidate this venue's cached extraction after a prompt change. */
  version: number;
  /** The page whose prose carries the programme. */
  url: string;
  /** Venue-specific hint appended to the extraction system prompt. */
  prompt?: string;
}

const VENUES: HtmlVenue[] = [
  {
    tag: "hamburger-studienbibliothek",
    version: 1,
    url: "https://www.studienbibliothek.org/index.shtml",
    prompt: `Quelle: Webseite der Hamburger Studienbibliothek (HSB), ein kritisch-theoretischer Bibliotheksverein in Hamburg-Rothenburgsort. Die Seite ist ein Nachrichten-Feed; extrahiere NUR konkrete, datierte Veranstaltungen (Konzerte, Vorträge, Diskussionen, Lesungen, Filmvorführungen mit Termin).
- Konzerte heißen "Bibliothekskonzert": setze title = "Bibliothekskonzert: <auftretende Künstler:innen oder Bandname>" und performers = die genannten Musiker:innen (mit Instrument, falls angegeben).
- Vorträge/Diskussionen/Lesungen: title = das inhaltliche Thema bzw. der Veranstaltungstitel; performers = Referent:in/Gäste, falls ausdrücklich genannt.
- Datum steht als "Wochentag, T. Monatsname JJJJ, HH Uhr" (z.B. "Montag, 22. Juni 2026, 20 Uhr"). Zeit wie "19.30 Uhr" wird zu "19:30".
- "Eintritt frei" → price_min = 0.
- IGNORIERE: reine Textveröffentlichungen ("Neuer Text", "Referat steht zur Verfügung"), Hinweise ohne eigenen Termin sowie Verweise auf bereits vergangene Filme/Videos ohne Veranstaltungsdatum.`,
  },
];

const here = dirname(fileURLToPath(import.meta.url));

await main();

async function main(): Promise<void> {
  const aiProxyUrl = process.env.AI_PROXY_URL;
  if (!aiProxyUrl) {
    err("AI_PROXY_URL not set — run: export AI_PROXY_URL=$(gh variable get AI_PROXY_URL)");
    process.exit(1);
  }
  const model = process.env.AI_PROXY_MODEL;
  const force = process.argv.includes("--force");
  const dryRun = process.argv.includes("--dry-run");

  const cache: ProgrammeEventsCache = { ...HTML_EVENTS_CACHE };
  let changed = false;

  for (const v of VENUES) {
    try {
      const { text, hash } = await fetchHtmlText(v.url);
      const existing = cache[v.tag];
      if (!force && existing && existing.hash === hash && existing.version === v.version) {
        err(`${v.tag}: unchanged (${existing.events.length} events) — skip`);
        continue;
      }
      err(`${v.tag}: extracting via ${new URL(aiProxyUrl).host} (${model ?? "gemini-2.5-flash"}) …`);
      const events = await eventsFromText(text, { aiProxyUrl, model, prompt: v.prompt });
      cache[v.tag] = { hash, version: v.version, events };
      changed = true;
      err(`${v.tag}: ${events.length} events extracted`);
    } catch (e) {
      err(`${v.tag}: FAILED — ${(e as Error).message}`);
    }
  }

  if (!changed) {
    err("no changes");
    return;
  }
  if (dryRun) {
    err("--dry-run: not writing");
    return;
  }
  await writeFile(resolve(here, "../src/data/html-events-cache.ts"), generateModule(cache), "utf8");
  err(`wrote src/data/html-events-cache.ts — ${Object.keys(cache).length} venue(s)`);
}

/** Deterministic module: top-level keys sorted; each entry a single JSON line
 *  (entry + event field order is fixed by the helper), so reruns are byte-stable. */
function generateModule(cache: ProgrammeEventsCache): string {
  const lines = Object.keys(cache)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(cache[k])},`);
  return `// Auto-generated by scripts/refresh-html-cache.ts — do not edit by hand.
import type { ProgrammeEventsCache } from "../programme-events";

export const HTML_EVENTS_CACHE: ProgrammeEventsCache = {
${lines.join("\n")}
};
`;
}

function err(msg: string): void {
  process.stderr.write(`[html-cache] ${msg}\n`);
}
