#!/usr/bin/env bun
/**
 * landau.today scrape pipeline. Drives the two source scrapers in parallel
 * and writes a typed `src/scrape-data.ts` bundle. Designed for the GitHub
 * Action and for local one-off runs.
 *
 *   1. scrapeKulturnetz()  — kulturnetz-landau.de (Django, schema.org microdata)
 *   2. scrapeLandauDe()    — www.landau.de (Advantic CMS, ICS feed + HTML cards)
 *
 * Stable ids are FNV-1a hashes of `(source | source_uid)`. Past events are
 * pruned at scrape time so the worker never has to.
 */
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { bundleSection, fnv1aInt, todayIso } from "@museumsufer/core";
import { scrapeKulturnetz } from "../src/scrapers/kulturnetz";
import { scrapeLandauDe } from "../src/scrapers/landau-de";
import type { Event, ScrapeData } from "../src/types";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const dataPath = resolve(root, "src/scrape-data.ts");

const startMain = Date.now();

const [knl, lde] = await Promise.all([
  stage("kulturnetz", () => scrapeKulturnetz()),
  stage("landau.de", () => scrapeLandauDe()),
]);

const merged = mergeAndId([...knl, ...lde]);
const today = todayIso();
const future = merged.filter((ev) => (ev.end_date ?? ev.date) >= today);
future.sort(eventSort);

await writeBundle(future);

const elapsed = ((Date.now() - startMain) / 1000).toFixed(1);
log(`done in ${elapsed}s — wrote ${future.length} events to ${dataPath}`);

// ─── helpers ────────────────────────────────────────────────────────

async function stage<T>(label: string, fn: () => Promise<T>): Promise<T> {
  const t0 = Date.now();
  log(`▶ ${label}`);
  try {
    const result = await fn();
    const ms = Date.now() - t0;
    if (Array.isArray(result)) log(`  ${label} → ${result.length} items (${ms}ms)`);
    else log(`  ${label} ok (${ms}ms)`);
    return result;
  } catch (err) {
    log(`  ${label} FAILED: ${(err as Error).message}`);
    throw err;
  }
}

function mergeAndId(events: Omit<Event, "id">[]): Event[] {
  // Cross-source dedup on (date, normalized title): the same event is
  // sometimes listed in both Kulturnetz and the city calendar (organizers
  // submit to both). Kulturnetz wins because its category data is
  // authoritative — the upstream URL slug already carries it.
  const byKey = new Map<string, Event>();
  const norm = (s: string) =>
    s
      .toLowerCase()
      .replace(/["»«]/g, "")
      .replace(/[^a-z0-9äöüß\s]/g, "")
      .replace(/\s+/g, " ")
      .trim();
  for (const ev of events) {
    const key = `${ev.date}|${norm(ev.title)}`;
    const id = fnv1aInt(`${ev.source}|${ev.source_uid}`);
    const existing = byKey.get(key);
    if (!existing) {
      byKey.set(key, { ...ev, id });
      continue;
    }
    if (ev.source === "kulturnetz" && existing.source !== "kulturnetz") {
      byKey.set(key, { ...ev, id });
    }
  }
  return [...byKey.values()];
}

function eventSort(a: Event, b: Event): number {
  return (
    a.date.localeCompare(b.date) ||
    (a.time ?? "99:99").localeCompare(b.time ?? "99:99") ||
    a.title.localeCompare(b.title, "de")
  );
}

async function writeBundle(events: Event[]): Promise<void> {
  const data: ScrapeData = { events, generatedAt: new Date().toISOString() };
  const lines: string[] = [
    "/* AUTO-GENERATED by scripts/scrape.ts — do not edit by hand. */",
    `import type { ScrapeData } from "./types";`,
    "",
    "export const SCRAPE_DATA: ScrapeData = {",
    bundleSection("events", events as unknown as Record<string, unknown>[]),
    `  generatedAt: ${JSON.stringify(data.generatedAt)},`,
    "};",
    "",
  ];
  await writeFile(dataPath, lines.join("\n"), "utf8");
}

function log(msg: string): void {
  console.error(`[${new Date().toISOString().slice(11, 19)}] ${msg}`);
}
