#!/usr/bin/env node
/**
 * Reads the minified bundle at public/styles.css (already produced by
 * lightningcss-cli) and emits src/styles-inline.ts so the worker can inline
 * the entire stylesheet in `<head>`. Inlining ~27 KB beats one render-blocking
 * round trip on cold loads — Lighthouse desktop's first-contentful-paint
 * insight flagged /styles.css as the only remaining blocker.
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const css = await readFile(resolve(root, "public/styles.css"), "utf8");
// Also pull fonts.css so its @font-face declarations ship inline.
// fonts.css would otherwise be a render-blocking <link rel="stylesheet">
// the audit flagged as adding ~150ms to LCP on cold loads. The woff2
// files themselves still come over the wire but the CSS round-trip
// is eliminated.
const fontsCss = await readFile(resolve(root, "public/fonts.css"), "utf8");

const combined = `${fontsCss}\n${css}`;
const escaped = combined.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const out = `// Auto-generated by scripts/inline-css.mjs — do not edit by hand.
export const INLINE_CSS = \`${escaped}\`;
`;

await writeFile(resolve(root, "src/styles-inline.ts"), out, "utf8");
console.log(`inline-css: wrote src/styles-inline.ts (${combined.length} chars, incl. fonts.css)`);
