import type { Genre, ScraperName } from "./types";

export interface VenueConfig {
  slug: string;
  name: string;
  short_name?: string;
  address: string;
  lat: number;
  lon: number;
  city: string;
  website_url: string;
  default_genre: Genre;
  scraper: ScraperName;
}

export const VENUES: VenueConfig[] = [
  {
    slug: "alte-oper",
    name: "Alte Oper Frankfurt",
    short_name: "Alte Oper",
    address: "Opernplatz 1, 60313 Frankfurt am Main",
    lat: 50.1158,
    lon: 8.6713,
    city: "frankfurt",
    website_url: "https://www.alteoper.de",
    default_genre: "classical",
    scraper: "alte-oper",
  },
  {
    slug: "oper-frankfurt",
    name: "Oper Frankfurt",
    short_name: "Oper Frankfurt",
    address: "Untermainanlage 11, 60311 Frankfurt am Main",
    lat: 50.1077,
    lon: 8.6726,
    city: "frankfurt",
    website_url: "https://oper-frankfurt.de",
    default_genre: "classical",
    scraper: "oper",
  },
  {
    slug: "dr-hochs-konservatorium",
    name: "Dr. Hoch's Konservatorium",
    short_name: "Dr. Hoch's",
    address: "Sonnemannstraße 16, 60314 Frankfurt am Main",
    lat: 50.1115,
    lon: 8.7016,
    city: "frankfurt",
    website_url: "https://www.dr-hochs.de",
    default_genre: "classical",
    scraper: "dr-hochs",
  },
  {
    slug: "hfmdk",
    name: "Hochschule für Musik und Darstellende Kunst Frankfurt",
    short_name: "HfMDK",
    address: "Eschersheimer Landstraße 29-39, 60322 Frankfurt am Main",
    lat: 50.1232,
    lon: 8.6749,
    city: "frankfurt",
    website_url: "https://www.hfmdk-frankfurt.de",
    default_genre: "classical",
    scraper: "hfmdk",
  },
  {
    slug: "ensemble-modern",
    name: "Ensemble Modern",
    short_name: "Ensemble Modern",
    address: "Schwedlerstraße 2-4, 60314 Frankfurt am Main",
    lat: 50.1125,
    lon: 8.7128,
    city: "frankfurt",
    website_url: "https://www.ensemble-modern.com",
    default_genre: "experimental",
    scraper: "ensemble-modern",
  },
  {
    slug: "hr-sinfonieorchester",
    name: "hr-Sinfonieorchester",
    short_name: "hr-Sinfonieorchester",
    address: "Bertramstraße 8, 60320 Frankfurt am Main",
    lat: 50.1314,
    lon: 8.6634,
    city: "frankfurt",
    website_url: "https://www.hr-sinfonieorchester.de",
    default_genre: "classical",
    scraper: "hr-sinfonieorchester",
  },
  {
    slug: "hr-bigband",
    name: "hr-Bigband",
    short_name: "hr-Bigband",
    address: "Bertramstraße 8, 60320 Frankfurt am Main",
    lat: 50.1314,
    lon: 8.6634,
    city: "frankfurt",
    website_url: "https://www.hr-bigband.de",
    default_genre: "jazz",
    scraper: "hr-bigband",
  },
  {
    slug: "holzhausenschloesschen",
    name: "Holzhausenschlösschen",
    short_name: "Holzhausenschlösschen",
    address: "Justinianstraße 5, 60322 Frankfurt am Main",
    lat: 50.1289,
    lon: 8.6764,
    city: "frankfurt",
    website_url: "https://www.frankfurter-buergerstiftung.de",
    default_genre: "chamber",
    scraper: "holzhausenschloesschen",
  },
  {
    slug: "jazz-frankfurt",
    name: "Jazz in Frankfurt",
    short_name: "jazz-frankfurt.de",
    address: "Frankfurt am Main",
    lat: 50.1109,
    lon: 8.6821,
    city: "frankfurt",
    website_url: "https://www.jazz-frankfurt.de",
    default_genre: "jazz",
    scraper: "jazz-frankfurt",
  },
  {
    slug: "jazz-palmengarten",
    name: "Jazz im Palmengarten",
    short_name: "Palmengarten",
    address: "Siesmayerstraße 61, 60323 Frankfurt am Main",
    lat: 50.1241,
    lon: 8.6584,
    city: "frankfurt",
    website_url: "https://www.palmengarten.de",
    default_genre: "jazz",
    scraper: "jazz-palmengarten",
  },
  {
    slug: "brotfabrik",
    name: "Brotfabrik",
    short_name: "Brotfabrik",
    address: "Bachmannstraße 2-4, 60488 Frankfurt am Main",
    lat: 50.1303,
    lon: 8.6071,
    city: "frankfurt",
    website_url: "https://www.brotfabrik.info",
    default_genre: "world",
    scraper: "brotfabrik",
  },
  {
    slug: "romanfabrik",
    name: "Romanfabrik",
    short_name: "Romanfabrik",
    address: "Hanauer Landstraße 186, 60314 Frankfurt am Main",
    lat: 50.1149,
    lon: 8.7124,
    city: "frankfurt",
    website_url: "https://www.romanfabrik.de",
    default_genre: "world",
    scraper: "romanfabrik",
  },
  {
    slug: "evangelische-akademie",
    name: "Evangelische Akademie Frankfurt",
    short_name: "Ev. Akademie",
    address: "Römerberg 9, 60311 Frankfurt am Main",
    lat: 50.1102,
    lon: 8.6824,
    city: "frankfurt",
    website_url: "https://www.evangelische-akademie.de",
    default_genre: "chamber",
    scraper: "evangelische-akademie",
  },
  {
    slug: "andreas-koehs",
    name: "Kirchenmusik Andreas Köhs",
    short_name: "Andreas Köhs",
    address: "Hasengasse 6, 60311 Frankfurt am Main",
    lat: 50.1115,
    lon: 8.6839,
    city: "frankfurt",
    website_url: "https://www.andreas-koehs.de",
    default_genre: "sacred",
    scraper: "andreas-koehs",
  },
  {
    slug: "kirchenmusik-dreikoenig",
    name: "Kirchenmusik Dreikönigsgemeinde",
    short_name: "Dreikönigskirche",
    address: "Färberstraße 41, 60594 Frankfurt am Main",
    lat: 50.1051,
    lon: 8.6863,
    city: "frankfurt",
    website_url: "https://www.dreikoenigsgemeinde.de",
    default_genre: "sacred",
    scraper: "kirchenmusik-dreikoenig",
  },
  {
    slug: "st-katharinen",
    name: "Kantorei St. Katharinen",
    short_name: "St. Katharinen",
    address: "An der Hauptwache 1, 60313 Frankfurt am Main",
    lat: 50.1138,
    lon: 8.679,
    city: "frankfurt",
    website_url: "https://www.st-katharinengemeinde.de",
    default_genre: "sacred",
    scraper: "stk-musik",
  },
  {
    slug: "kronberg-academy",
    name: "Kronberg Academy / Casals Forum",
    short_name: "Kronberg Academy",
    address: "Hainstraße 11, 61476 Kronberg im Taunus",
    lat: 50.1828,
    lon: 8.5202,
    city: "kronberg",
    website_url: "https://www.kronbergacademy.de",
    default_genre: "classical",
    scraper: "kronberg-academy",
  },
  {
    slug: "rheingau-musikfestival",
    name: "Rheingau Musik Festival",
    short_name: "Rheingau Festival",
    address: "Postfach 1125, 65367 Oestrich-Winkel",
    lat: 50.0058,
    lon: 8.0464,
    city: "eltville",
    website_url: "https://www.rheingau-musik-festival.de",
    default_genre: "classical",
    scraper: "rheingau-festival",
  },
  {
    slug: "bad-homburger-schlosskonzerte",
    name: "Bad Homburger Schlosskonzerte",
    short_name: "Bad Homburger Schloss",
    address: "Schloss Bad Homburg, 61348 Bad Homburg vor der Höhe",
    lat: 50.2275,
    lon: 8.6172,
    city: "bad-homburg",
    website_url: "https://www.bad-homburger-schlosskonzerte.de",
    default_genre: "classical",
    scraper: "bad-homburg-schloss",
  },
  {
    slug: "denkbar",
    name: "Denkbar Frankfurt",
    short_name: "Denkbar",
    address: "Spohrstraße 46a, 60327 Frankfurt am Main",
    lat: 50.1189,
    lon: 8.6601,
    city: "frankfurt",
    website_url: "https://denkbar-ffm.de",
    default_genre: "jazz",
    scraper: "denkbar",
  },
  {
    slug: "bad-soden",
    name: "Bad Sodener Kammerkonzerte",
    short_name: "Bad Soden",
    address: "Kurpark, 65812 Bad Soden am Taunus",
    lat: 50.1411,
    lon: 8.4985,
    city: "bad-soden",
    website_url: "https://www.bad-soden.de",
    default_genre: "chamber",
    scraper: "bad-soden",
  },
];
