#!/usr/bin/env bun
/**
 * Drives the hub's full scrape cycle: loads the existing canonical events,
 * runs every registered venue scraper, applies the keyword-pass classifier,
 * merges results, and writes data/events.ts. Output is deterministic — two
 * consecutive runs on identical upstream data produce a byte-identical file
 * so the GH Action's commit-if-changed step stays quiet.
 */
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { stringifyRecord } from "@museumsufer/core/bundle-writer";
import { EVENTS as PREVIOUS_EVENTS } from "../data/events";
import { VENUE_NAMES as PREVIOUS_VENUE_NAMES } from "../data/venue-names";
import { runHub } from "../src/runner";
import type { EventHubData } from "../src/types";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

await main();

async function main(): Promise<void> {
  const previous: EventHubData = { events: [...PREVIOUS_EVENTS], venueNames: { ...PREVIOUS_VENUE_NAMES } };
  const proxy = process.env.FETCH_PROXY_URL
    ? { url: process.env.FETCH_PROXY_URL, token: process.env.FETCH_PROXY_TOKEN }
    : null;
  if (proxy) log(`fetch-proxy configured: ${new URL(proxy.url).host}`);
  const next = await runHub(previous, { log, proxy });
  await writeFile(resolve(root, "data/events.ts"), generateModule(next), "utf8");
  log(`wrote data/events.ts — ${next.events.length} events`);
  await writeFile(resolve(root, "data/venue-names.ts"), generateNamesModule(next.venueNames ?? {}), "utf8");
  log(`wrote data/venue-names.ts — ${Object.keys(next.venueNames ?? {}).length} venues`);
  summariseLabels(next);
}

function generateNamesModule(names: Record<string, string>): string {
  const lines = Object.entries(names).map(([slug, name]) => `  ${JSON.stringify(slug)}: ${JSON.stringify(name)},`);
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.
export const VENUE_NAMES: Readonly<Record<string, string>> = {
${lines.join("\n")}
};
`;
}

function generateModule(data: EventHubData): string {
  // Each record is prefixed with a `<CanonicalEvent>` type assertion so TS
  // doesn't try to compute the array literal's element type as a union of
  // every record's structural type — at ~1500+ events that union explodes
  // into TS2590. With the per-record assertion, the array's element type
  // is uniformly CanonicalEvent and inference stays cheap.
  const records = data.events.map(
    (e) => `<CanonicalEvent>${stringifyRecord(e as unknown as Record<string, unknown>)}`,
  );
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.
import type { CanonicalEvent } from "../src/types";

export const EVENTS: readonly CanonicalEvent[] = [
  ${records.join(",\n  ")}
];
`;
}

function summariseLabels(data: EventHubData): void {
  const counts = new Map<string, number>();
  for (const ev of data.events) {
    for (const l of ev.labels) counts.set(l.label, (counts.get(l.label) ?? 0) + 1);
  }
  const rows = Array.from(counts.entries()).sort((a, b) => b[1] - a[1]);
  for (const [label, n] of rows) log(`  ${label.padEnd(28)} ${n}`);
}

function log(msg: string): void {
  process.stderr.write(`[event-hub] ${msg}\n`);
}
