#!/usr/bin/env bun
/**
 * Drives the hub's full scrape cycle: loads the existing canonical events,
 * runs every registered venue scraper, applies the keyword-pass classifier,
 * merges results, and writes data/events.ts. Output is deterministic — two
 * consecutive runs on identical upstream data produce a byte-identical file
 * so the GH Action's commit-if-changed step stays quiet.
 */
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { stringifyRecord } from "@museumsufer/core/bundle-writer";
import { EVENTS as PREVIOUS_EVENTS } from "../data/events";
import { TMDB_POSTER_CACHE, type TmdbCacheEntry } from "../data/tmdb-cache";
import { VENUE_NAMES as PREVIOUS_VENUE_NAMES } from "../data/venue-names";
import { runHub } from "../src/runner";
import type { EventHubData } from "../src/types";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

await main();

async function main(): Promise<void> {
  const previous: EventHubData = { events: [...PREVIOUS_EVENTS], venueNames: { ...PREVIOUS_VENUE_NAMES } };
  const proxy = process.env.FETCH_PROXY_URL
    ? { url: process.env.FETCH_PROXY_URL, token: process.env.FETCH_PROXY_TOKEN }
    : null;
  if (proxy) log(`fetch-proxy configured: ${new URL(proxy.url).host}`);

  const tmdbCache: Record<string, TmdbCacheEntry | null> = { ...TMDB_POSTER_CACHE };
  const beforeCacheJson = JSON.stringify(tmdbCache);

  // Phase 1: scrape + merge (no enrichment) → write bundle immediately.
  // This ensures the committed events.ts always reflects the latest scrape
  // even if the enrichment pass (TMDb/DeepL/OMDb) times out in CI.
  const next = await runHub(previous, {
    log,
    proxy,
    skipEnrichment: true,
  });
  await writeFile(resolve(root, "data/events.ts"), generateModule(next), "utf8");
  log(`wrote data/events.ts — ${next.events.length} events`);
  await writeFile(resolve(root, "data/venue-names.ts"), generateNamesModule(next.venueNames ?? {}), "utf8");
  log(`wrote data/venue-names.ts — ${Object.keys(next.venueNames ?? {}).length} venues`);

  // Phase 2: enrich (TMDb posters + DeepL + OMDb ratings). Mutates
  // events in place and fills tmdbCache. Non-fatal on timeout — the
  // bundle is already written; the cache persists partial results.
  const { enrichFilmPosters } = await import("../src/tmdb");
  await enrichFilmPosters(next.events, {
    apiKey: process.env.TMDB_API_KEY,
    cache: tmdbCache,
    deeplApiKeys: process.env.DEEPL_API_KEYS,
    omdbApiKey: process.env.OMDB_API_KEY,
    log,
  });

  // Rewrite events.ts with enrichment data (poster URLs, descriptions, ratings).
  await writeFile(resolve(root, "data/events.ts"), generateModule(next), "utf8");
  log(`rewrote data/events.ts with enrichment`);

  // Persist TMDb/OMDb cache when anything changed.
  if (JSON.stringify(tmdbCache) !== beforeCacheJson) {
    await writeFile(resolve(root, "data/tmdb-cache.ts"), generateTmdbCacheModule(tmdbCache), "utf8");
    log(`wrote data/tmdb-cache.ts — ${Object.keys(tmdbCache).length} entries`);
  }
  summariseLabels(next);
}

function generateNamesModule(names: Record<string, string>): string {
  const lines = Object.entries(names).map(([slug, name]) => `  ${JSON.stringify(slug)}: ${JSON.stringify(name)},`);
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.
export const VENUE_NAMES: Readonly<Record<string, string>> = {
${lines.join("\n")}
};
`;
}

function generateTmdbCacheModule(cache: Record<string, TmdbCacheEntry | null>): string {
  const lines = Object.keys(cache)
    .sort()
    .map((key) => {
      const entry = cache[key];
      const value = entry === null ? "null" : JSON.stringify(entry);
      return `  ${JSON.stringify(key)}: ${value},`;
    });
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.

export interface TmdbCacheEntry {
  id: number;
  poster: string | null;
  title?: string;
  title_en?: string;
  overview?: string;
  overview_en?: string;
  kind?: "movie" | "tv";
  genre_ids?: number[];
  vote_average?: number;
  vote_count?: number;
  imdb_id?: string;
  rt_critic?: number;
  rt_url?: string;
  imdb_rating?: number;
  imdb_votes?: number;
}

export const TMDB_POSTER_CACHE: Record<string, TmdbCacheEntry | null> = {
${lines.join("\n")}
};
`;
}

function generateModule(data: EventHubData): string {
  // Each record is prefixed with a `<CanonicalEvent>` type assertion so TS
  // doesn't try to compute the array literal's element type as a union of
  // every record's structural type — at ~1500+ events that union explodes
  // into TS2590. With the per-record assertion, the array's element type
  // is uniformly CanonicalEvent and inference stays cheap.
  const records = data.events.map(
    (e) => `<CanonicalEvent>${stringifyRecord(e as unknown as Record<string, unknown>)}`,
  );
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.
import type { CanonicalEvent } from "../src/types";

export const EVENTS: readonly CanonicalEvent[] = [
  ${records.join(",\n  ")}
];
`;
}

function summariseLabels(data: EventHubData): void {
  const counts = new Map<string, number>();
  for (const ev of data.events) {
    for (const l of ev.labels) counts.set(l.label, (counts.get(l.label) ?? 0) + 1);
  }
  const rows = Array.from(counts.entries()).sort((a, b) => b[1] - a[1]);
  for (const [label, n] of rows) log(`  ${label.padEnd(28)} ${n}`);
}

function log(msg: string): void {
  process.stderr.write(`[event-hub] ${msg}\n`);
}
