// Auto-generated by scripts/scrape.ts — do not edit by hand.
import type { TheaterConfig } from "./theater-config";

export const SYNTHESIZED_THEATERS: TheaterConfig[] = [
  {
    slug: "brotfabrik",
    name: "Brotfabrik",
    address: "",
    lat: 50.1303,
    lon: 8.6071,
    website_url: "https://www.brotfabrik.de",
    ticketing_provider: null,
  },
];
