import { SYNTHESIZED_THEATERS } from "./synthesized-theaters";
import type { TicketingProvider } from "./types";

export interface TheaterConfig {
  slug: string;
  name: string;
  address: string;
  lat: number;
  lon: number;
  website_url: string;
  ticketing_provider: TicketingProvider;
}

/** Hand-curated theater list. Combined with auto-generated
 *  SYNTHESIZED_THEATERS (from scripts/scrape.ts) below to form the final
 *  THEATERS export. */
export const CURATED_THEATERS: TheaterConfig[] = [
  {
    slug: "schauspiel-frankfurt",
    name: "Schauspiel Frankfurt",
    address: "Neue Mainzer Straße 17, 60311 Frankfurt am Main",
    lat: 50.1078,
    lon: 8.6745,
    website_url: "https://www.schauspielfrankfurt.de",
    ticketing_provider: "eventim_inhouse",
  },
  {
    slug: "oper-frankfurt",
    name: "Oper Frankfurt",
    address: "Untermainanlage 11, 60311 Frankfurt am Main",
    lat: 50.1077,
    lon: 8.6726,
    website_url: "https://oper-frankfurt.de",
    ticketing_provider: "eventim_inhouse",
  },
  {
    slug: "english-theatre-frankfurt",
    name: "The English Theatre Frankfurt",
    address: "Gallusanlage 7, 60329 Frankfurt am Main",
    lat: 50.1083,
    lon: 8.6712,
    website_url: "https://english-theatre.de",
    ticketing_provider: "eventim_inhouse",
  },
  {
    slug: "komoedie-frankfurt",
    name: "Die Komödie Frankfurt",
    address: "Neue Mainzer Straße 18, 60311 Frankfurt am Main",
    lat: 50.1086,
    lon: 8.6739,
    website_url: "https://diekomoedie.de",
    ticketing_provider: "custom",
  },
  {
    slug: "mousonturm",
    name: "Künstlerhaus Mousonturm",
    address: "Waldschmidtstraße 4, 60316 Frankfurt am Main",
    lat: 50.1183,
    lon: 8.7019,
    website_url: "https://www.mousonturm.de",
    ticketing_provider: "reservix",
  },
  {
    slug: "neues-theater-hoechst",
    name: "Neues Theater Höchst",
    address: "Emmerich-Josef-Straße 46a, 65929 Frankfurt am Main",
    lat: 50.1014,
    lon: 8.5443,
    website_url: "https://neues-theater.de",
    ticketing_provider: "custom",
  },
  {
    slug: "volksbuehne-frankfurt",
    name: "Volksbühne im Großen Hirschgraben",
    address: "Großer Hirschgraben 19, 60311 Frankfurt am Main",
    lat: 50.1116,
    lon: 8.6817,
    website_url: "https://volksbuehne.net",
    ticketing_provider: "reservix",
  },
  {
    slug: "stalburg-theater",
    name: "Stalburg Theater",
    address: "Glauburgstraße 80, 60318 Frankfurt am Main",
    lat: 50.1294,
    lon: 8.6885,
    website_url: "https://stalburg.de",
    ticketing_provider: "reservix",
  },
  {
    slug: "tigerpalast-variete",
    name: "Tigerpalast Varieté",
    address: "Heiligkreuzgasse 16-20, 60313 Frankfurt am Main",
    lat: 50.1146,
    lon: 8.6836,
    website_url: "https://www.tigerpalast.de",
    ticketing_provider: "reservix",
  },
  {
    slug: "die-schmiere",
    name: "Die Schmiere",
    address: "Seckbächer Gasse 8, 60311 Frankfurt am Main",
    lat: 50.1112,
    lon: 8.6833,
    website_url: "https://die-schmiere.de",
    ticketing_provider: "reservix",
  },
  {
    slug: "dresden-frankfurt-dance-company",
    name: "Dresden Frankfurt Dance Company",
    address: "Bockenheimer Depot, Carlo-Schmid-Platz 1, 60486 Frankfurt am Main",
    lat: 50.1205,
    lon: 8.6463,
    website_url: "https://www.dfdc.de",
    ticketing_provider: "eventim_inhouse",
  },
  {
    slug: "dramatische-buehne",
    name: "Die Dramatische Bühne",
    address: "Frankfurt am Main",
    lat: 50.1109,
    lon: 8.6821,
    website_url: "https://www.diedramatischebuehne.de",
    ticketing_provider: "custom",
  },
  {
    slug: "theater-willy-praml",
    name: "Theater Willy Praml",
    address: "Naxoshalle, Waldschmidtstraße 19, 60316 Frankfurt am Main",
    lat: 50.1199,
    lon: 8.7037,
    website_url: "https://theaterwillypraml.de",
    ticketing_provider: "custom",
  },
  {
    slug: "kellertheater-frankfurt",
    name: "Kellertheater Frankfurt",
    address: "Mainstraße 2, 60311 Frankfurt am Main",
    lat: 50.1108,
    lon: 8.6852,
    website_url: "https://www.kellertheater-frankfurt.de",
    ticketing_provider: "frankfurt_ticket",
  },
  {
    slug: "gallus-theater",
    name: "Gallus Theater",
    address: "Kleyerstraße 15, 60326 Frankfurt am Main",
    lat: 50.101,
    lon: 8.6334,
    website_url: "https://www.gallustheater.de",
    ticketing_provider: "custom",
  },
  {
    slug: "theaterhaus-frankfurt",
    name: "Theaterhaus Frankfurt",
    address: "Schützenstraße 12, 60311 Frankfurt am Main",
    lat: 50.1116,
    lon: 8.6877,
    website_url: "https://www.theaterhaus-frankfurt.de",
    ticketing_provider: "custom",
  },
  {
    slug: "internationales-theater",
    name: "Internationales Theater Frankfurt",
    address: "Hanauer Landstraße 5-7, 60314 Frankfurt am Main",
    lat: 50.1135,
    lon: 8.6976,
    website_url: "https://www.internationales-theater.de",
    ticketing_provider: "custom",
  },
  {
    slug: "papageno-musiktheater",
    name: "Papageno Musiktheater",
    address: "Palmengartenstraße 11, 60325 Frankfurt am Main",
    lat: 50.1228,
    lon: 8.6533,
    website_url: "https://www.papageno-theater.de",
    ticketing_provider: "frankfurt_ticket",
  },
  {
    slug: "galli-theater",
    name: "Galli Theater Frankfurt",
    address: "Hasengasse 2, 60311 Frankfurt am Main",
    lat: 50.1116,
    lon: 8.6841,
    website_url: "https://www.galli-frankfurt.de",
    ticketing_provider: "custom",
  },
  {
    slug: "theater-alte-bruecke",
    name: "Theater Alte Brücke",
    address: "Alte Brücke 4, 60594 Frankfurt am Main",
    lat: 50.1078,
    lon: 8.6874,
    website_url: "https://www.theater-alte-bruecke.de",
    ticketing_provider: "reservix",
  },
  {
    slug: "die-kaes",
    name: "Die Käs",
    address: "Waldschmidtstraße 19, 60316 Frankfurt am Main",
    lat: 50.1196,
    lon: 8.7041,
    website_url: "https://www.diekaes.de",
    ticketing_provider: "reservix",
  },
  {
    slug: "theater-lempenfieber",
    name: "Theater Lempenfieber",
    address: "Berkersheimer Weg 31, 60433 Frankfurt am Main",
    lat: 50.1856,
    lon: 8.6824,
    website_url: "https://www.lempenfieber.de",
    ticketing_provider: "reservix",
  },
  {
    slug: "landungsbruecken",
    name: "Landungsbrücken Frankfurt",
    address: "Gutleutstraße 294, 60327 Frankfurt am Main",
    lat: 50.0976,
    lon: 8.6519,
    website_url: "https://landungsbruecken.org",
    ticketing_provider: "custom",
  },
];

export const THEATERS: TheaterConfig[] = [...CURATED_THEATERS, ...SYNTHESIZED_THEATERS];
