export interface Env {
  DB: D1Database;
  FEEDBACK_EMAIL: SendEmail;
  VAPID_PUBLIC_KEY?: string;
  VAPID_PRIVATE_KEY?: string;
  VAPID_SUBJECT?: string;
}

export type AvailabilityStatus = "unknown" | "available" | "few_left" | "sold_out" | "cancelled";

export type TicketingProvider = "eventim_inhouse" | "frankfurt_ticket" | "reservix" | "wordpress" | "custom" | null;

// Theater metadata lives in src/theater-config.ts (TheaterConfig) — no
// DB-row interface needed here.

// Optional-rather-than-nullable on the rarely-set fields. The scrape
// generator strips null/undefined values from the JSON to keep
// scrape-data.ts compact, so any field that's frequently null lands as
// "absent" in the bundled data. Consumers use `?? null` / `?.` already,
// so the undefined-vs-null distinction never reaches a renderer.
export interface Show {
  id: number;
  theater_slug: string;
  slug: string;
  title: string;
  subtitle?: string;
  description?: string;
  language?: string;
  age_recommendation?: string;
  image_url?: string;
  detail_url?: string;
  season?: string;
}

export interface Performance {
  id: number;
  show_id: number;
  date: string;
  status: AvailabilityStatus;
  time?: string;
  end_time?: string;
  end_date?: string;
  venue_room?: string;
  provider_event_id?: string;
  ticket_url?: string;
  price_min?: number;
  price_max?: number;
}

export interface ScrapedShow {
  slug: string;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  language?: string | null;
  age_recommendation?: string | null;
  image_url?: string | null;
  detail_url?: string | null;
  season?: string | null;
}

export interface ScrapedPerformance {
  show_slug: string;
  date: string;
  time: string | null;
  end_time?: string | null;
  end_date?: string | null;
  venue_room?: string | null;
  provider_event_id?: string | null;
  ticket_url?: string | null;
  status?: AvailabilityStatus;
  price_min?: number | null;
  price_max?: number | null;
}

export interface ScrapeResult {
  theater_slug: string;
  shows: ScrapedShow[];
  performances: ScrapedPerformance[];
}

/** Bundle of all scraped state that ships with the worker, generated by
 *  scripts/scrape.ts. Reads at runtime go through this in-memory shape
 *  instead of D1 (drops the SCRAPE_SECRET dance and makes diffs reviewable). */
export interface ScrapeData {
  shows: Show[];
  performances: Performance[];
}
