export interface Env {
  DB: D1Database;
}

export type AvailabilityStatus = "unknown" | "available" | "few_left" | "sold_out" | "cancelled";

export type TicketingProvider = "eventim_inhouse" | "frankfurt_ticket" | "reservix" | "wordpress" | "custom" | null;

// Theater metadata lives in src/theater-config.ts (TheaterConfig) — no
// DB-row interface needed here.

export interface Show {
  id: number;
  theater_slug: string;
  slug: string;
  title: string;
  subtitle: string | null;
  description: string | null;
  language: string | null;
  age_recommendation: string | null;
  image_url: string | null;
  detail_url: string | null;
  season: string | null;
}

export interface Performance {
  id: number;
  show_id: number;
  date: string;
  time: string | null;
  end_time: string | null;
  end_date: string | null;
  venue_room: string | null;
  provider_event_id: string | null;
  ticket_url: string | null;
  status: AvailabilityStatus;
  available_seats: number | null;
  total_seats: number | null;
  price_min: number | null;
  price_max: number | null;
  currency: string | null;
  availability_checked_at: string | null;
}

export interface ScrapedShow {
  slug: string;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  language?: string | null;
  age_recommendation?: string | null;
  image_url?: string | null;
  detail_url?: string | null;
  season?: string | null;
}

export interface ScrapedPerformance {
  show_slug: string;
  date: string;
  time: string | null;
  end_time?: string | null;
  end_date?: string | null;
  venue_room?: string | null;
  provider_event_id?: string | null;
  ticket_url?: string | null;
  status?: AvailabilityStatus;
  price_min?: number | null;
  price_max?: number | null;
}

export interface ScrapeResult {
  theater_slug: string;
  shows: ScrapedShow[];
  performances: ScrapedPerformance[];
}

/** Bundle of all scraped state that ships with the worker, generated by
 *  scripts/scrape.ts. Reads at runtime go through this in-memory shape
 *  instead of D1 (drops the SCRAPE_SECRET dance and makes diffs reviewable). */
export interface ScrapeData {
  shows: Show[];
  performances: Performance[];
}
