import { SYNTHESIZED_CINEMAS } from "./synthesized-cinemas";

export interface CinemaConfig {
  slug: string;
  name: string;
  short_name?: string;
  address: string;
  lat: number;
  lon: number;
  city: string;
  website_url: string;
  /** Short editorial blurb shown on the cinema's hero. */
  tagline?: string;
}

/** Hand-curated cinema list. Combined with auto-generated SYNTHESIZED_CINEMAS
 *  (from scripts/scrape.ts) below to form the final CINEMAS export. */
export const CURATED_CINEMAS: CinemaConfig[] = [
  {
    slug: "astor-frankfurt",
    name: "Astor Film Lounge MyZeil",
    short_name: "Astor Film Lounge",
    address: "Zeil 106, 60313 Frankfurt am Main",
    lat: 50.1136,
    lon: 8.6856,
    city: "frankfurt",
    website_url: "https://www.astor-filmlounge.de/frankfurt",
    tagline: "Premium-Programmkino im MyZeil.",
  },
  {
    slug: "cinema-frankfurt",
    name: "Cinéma Frankfurt",
    short_name: "Cinéma",
    address: "Roßmarkt 7, 60311 Frankfurt am Main",
    lat: 50.1132,
    lon: 8.6786,
    city: "frankfurt",
    website_url: "https://www.arthouse-kinos.de",
    tagline: "Arthouse-Kino im Herzen der Innenstadt.",
  },
  {
    slug: "eldorado-frankfurt",
    name: "Eldorado Arthouse Kino",
    short_name: "Eldorado",
    address: "Schäfergasse 29, 60313 Frankfurt am Main",
    lat: 50.1138,
    lon: 8.6843,
    city: "frankfurt",
    website_url: "https://www.arthouse-kinos.de",
    tagline: "Eines der ältesten Programmkinos der Stadt.",
  },
  {
    slug: "harmonie-frankfurt",
    name: "Harmonie Theater Frankfurt",
    short_name: "Harmonie",
    address: "Dreieichstraße 54, 60594 Frankfurt am Main",
    lat: 50.0976,
    lon: 8.6818,
    city: "frankfurt",
    website_url: "https://www.arthouse-kinos.de",
    tagline: "Programmkino in Sachsenhausen.",
  },
  {
    slug: "orfeos-erben",
    name: "Orfeo's Erben",
    short_name: "Orfeo's Erben",
    address: "Hamburger Allee 45, 60486 Frankfurt am Main",
    lat: 50.1149,
    lon: 8.6452,
    city: "frankfurt",
    website_url: "https://www.orfeos.de",
    tagline: "Kino, Restaurant und Bar im Bockenheim.",
  },
  {
    slug: "dff-deutsches-filminstitut-filmmuseum",
    name: "DFF — Deutsches Filminstitut & Filmmuseum",
    short_name: "DFF Filmmuseum",
    address: "Schaumainkai 41, 60596 Frankfurt am Main",
    lat: 50.1042,
    lon: 8.6727,
    city: "frankfurt",
    website_url: "https://www.dff.film",
    tagline: "Kinematographische Erbe-Pflege am Museumsufer.",
  },
  {
    slug: "filmforum-hoechst",
    name: "Filmforum Höchst",
    short_name: "Filmforum Höchst",
    address: "Emmerich-Josef-Straße 46a, 65929 Frankfurt am Main",
    lat: 50.1014,
    lon: 8.5443,
    city: "frankfurt",
    website_url: "https://www.filmforum-hoechst.de",
    tagline: "Kommunales Kino im Stadtteil Höchst.",
  },
  {
    slug: "pupille",
    name: "Pupille — Kino in der Uni",
    short_name: "Pupille",
    address: "Norbert-Wollheim-Platz 1, 60323 Frankfurt am Main",
    lat: 50.1265,
    lon: 8.668,
    city: "frankfurt",
    website_url: "https://www.pupille.org",
    tagline: "Studierendenkino am Campus Westend.",
  },
  {
    slug: "nippon-connection",
    name: "Nippon Connection",
    short_name: "Nippon Connection",
    address: "Mousonturm, Waldschmidtstraße 4, 60316 Frankfurt am Main",
    lat: 50.1183,
    lon: 8.7019,
    city: "frankfurt",
    website_url: "https://www.nipponconnection.com",
    tagline: "Festival des japanischen Films.",
  },
  {
    slug: "murnau-filmtheater",
    name: "Murnau-Filmtheater",
    short_name: "Murnau-Filmtheater",
    address: "Murnaustraße 6, 65189 Wiesbaden",
    lat: 50.0857,
    lon: 8.2456,
    city: "wiesbaden",
    website_url: "https://murnau-stiftung.de/murnau-filmtheater",
    tagline: "Heimspielort der Friedrich-Wilhelm-Murnau-Stiftung.",
  },
  {
    slug: "caligari-wiesbaden",
    name: "Caligari FilmBühne",
    short_name: "Caligari",
    address: "Marktplatz 9, 65183 Wiesbaden",
    lat: 50.083,
    lon: 8.2412,
    city: "wiesbaden",
    website_url: "https://www.wiesbaden.de/caligari",
    tagline: "Kommunales Kino der Stadt Wiesbaden.",
  },
  {
    slug: "capitol-mainz",
    name: "Capitol Arthouse Kino Mainz",
    short_name: "Capitol Mainz",
    address: "Neubrunnenstraße 9, 55116 Mainz",
    lat: 50.0046,
    lon: 8.2693,
    city: "mainz",
    website_url: "https://www.arthouse-mainz.de",
    tagline: "Arthouse-Programm in der Mainzer Altstadt.",
  },
  {
    slug: "filmpalast-hofheim",
    name: "Filmpalast Hofheim",
    short_name: "Filmpalast Hofheim",
    address: "Chinonplatz 4, 65719 Hofheim am Taunus",
    lat: 50.0861,
    lon: 8.4483,
    city: "hofheim",
    website_url: "https://www.filmpalast-hofheim.de",
    tagline: "Traditionskino am Taunusrand.",
  },
  {
    slug: "kino-kelkheim",
    name: "Kino Kelkheim",
    short_name: "Kino Kelkheim",
    address: "Bahnstraße 4, 65779 Kelkheim",
    lat: 50.1474,
    lon: 8.4501,
    city: "kelkheim",
    website_url: "https://www.kino-kelkheim.de",
  },
  {
    slug: "kronberger-lichtspiele",
    name: "Kronberger Lichtspiele",
    short_name: "Kronberger Lichtspiele",
    address: "Friedrich-Ebert-Straße 1, 61476 Kronberg im Taunus",
    lat: 50.1795,
    lon: 8.5102,
    city: "kronberg",
    website_url: "https://www.kronberger-lichtspiele.de",
  },
  {
    slug: "kino-alte-muehle-bad-vilbel",
    name: "Kino Alte Mühle",
    short_name: "Alte Mühle",
    address: "Lohstraße 13, 61118 Bad Vilbel",
    lat: 50.1846,
    lon: 8.7464,
    city: "bad-vilbel",
    website_url: "https://www.kino-alte-muehle.de",
  },
  {
    slug: "kino-koeppern",
    name: "Kino Köppern",
    short_name: "Kino Köppern",
    address: "Usinger Straße 8, 61381 Friedrichsdorf",
    lat: 50.2554,
    lon: 8.6453,
    city: "friedrichsdorf",
    website_url: "https://www.kino-koeppern.de",
  },
  {
    slug: "lichtblick-moerfelden",
    name: "Lichtblick Mörfelden",
    short_name: "Lichtblick",
    address: "Westendstraße 60, 64546 Mörfelden-Walldorf",
    lat: 50.0001,
    lon: 8.5709,
    city: "moerfelden-walldorf",
    website_url: "https://www.kino-lichtblick.de",
  },
  {
    slug: "programmkino-rex",
    name: "Programmkino Rex",
    short_name: "Rex Darmstadt",
    address: "Grafenstraße 35, 64283 Darmstadt",
    lat: 49.8773,
    lon: 8.6555,
    city: "darmstadt",
    website_url: "https://www.rex-kino-darmstadt.de",
    tagline: "Filmkultur im Herzen der Wissenschaftsstadt.",
  },
  {
    slug: "filmkreis-darmstadt",
    name: "Filmkreis TU Darmstadt",
    short_name: "Filmkreis TU",
    address: "Hochschulstraße 1, 64289 Darmstadt",
    lat: 49.8746,
    lon: 8.6557,
    city: "darmstadt",
    website_url: "https://www.filmkreis.tu-darmstadt.de",
    tagline: "Studierendenkino an der TU Darmstadt.",
  },
];

export const CINEMAS: CinemaConfig[] = [...CURATED_CINEMAS, ...SYNTHESIZED_CINEMAS];
