// Auto-generated by scripts/scrape.ts — do not edit by hand.
import type { CinemaConfig } from "./cinema-config";

export const SYNTHESIZED_CINEMAS: CinemaConfig[] = [
  {
    slug: "dfg-frankfurt",
    name: "Deutsch-Französische Gesellschaft Frankfurt",
    address: "",
    lat: 50.1109,
    lon: 8.6736,
    city: "frankfurt",
    website_url: "https://www.dfg-frankfurt.de",
  },
  {
    slug: "eschborn-k",
    name: "Eschborn K",
    address: "",
    lat: 50.1457,
    lon: 8.571,
    city: "frankfurt",
    website_url: "https://eschborn-k.de",
  },
  {
    slug: "malsehn",
    name: "Mal seh'n Kino",
    address: "",
    lat: 50.1235,
    lon: 8.6789,
    city: "frankfurt",
    website_url: "https://malsehnkino.de",
  },
  {
    slug: "museum-giersch-der-goethe-universitaet",
    name: "MGGU – Museum Giersch der Goethe-Universität",
    address: "",
    lat: 50.0986,
    lon: 8.6545,
    city: "frankfurt",
    website_url: "https://www.mggu.de",
  },
  {
    slug: "senckenberg-naturmuseum",
    name: "Senckenberg Naturmuseum",
    address: "",
    lat: 50.1175,
    lon: 8.6522,
    city: "frankfurt",
    website_url: "https://museumfrankfurt.senckenberg.de",
  },
];
