#!/usr/bin/env node
/**
 * Copies vendored assets out of node_modules into the app's public/ dir
 * so the worker can serve them locally — replacing previous reliance on
 * https://fonts.googleapis.com and any third-party CDN.
 *
 *   bun ../../scripts/sync-assets.mjs [appDir]
 *
 * appDir defaults to process.cwd() so each app calls it without args.
 *
 * Inputs come from <appDir>/scripts/assets.config.mjs which exports:
 *   { fonts: FontSpec[], htmx?: boolean }
 *
 * FontSpec = {
 *   pkg: "@fontsource-variable/fraunces" | "@fontsource/dm-mono" | …
 *   css: string[]                  // one or more *.css entry files inside pkg
 *   subsets?: string[]             // restrict to these (e.g. ["latin","latin-ext"])
 *   familyAlias?: [string,string]  // rename "Fraunces Variable" → "Fraunces" in output
 * }
 *
 * Output:
 *   public/htmx.min.js     (if htmx: true)
 *   public/fonts/*.woff2
 *   public/fonts.css       (concatenated, rewritten urls, alias applied)
 */
import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const appDir = resolve(process.argv[2] ?? process.cwd());
const configPath = resolve(appDir, "scripts/assets.config.mjs");
if (!existsSync(configPath)) {
  console.error(`sync-assets: no config at ${configPath}`);
  process.exit(1);
}
const { fonts = [], htmx = true } = (await import(pathToFileURL(configPath).href)).default;

const fontsDir = resolve(appDir, "public/fonts");
await rm(fontsDir, { recursive: true, force: true });
await mkdir(fontsDir, { recursive: true });

const pickedFiles = new Set();
const sections = [];

for (const spec of fonts) {
  const pkgRoot = resolveFromAnyNodeModules(spec.pkg);
  for (const css of spec.css) {
    const cssPath = resolve(pkgRoot, css);
    const raw = await readFile(cssPath, "utf8");
    const blocks = splitFontFaceBlocks(raw);
    for (const block of blocks) {
      if (spec.subsets && !blockMatchesSubsets(block, spec.subsets)) continue;
      let rewritten = block;
      if (spec.familyAlias) {
        const [from, to] = spec.familyAlias;
        rewritten = rewritten.replaceAll(`'${from}'`, `'${to}'`).replaceAll(`"${from}"`, `"${to}"`);
      }
      rewritten = rewritten.replace(/url\(\.\/files\/([^)]+)\)/g, (_m, fname) => {
        const src = resolve(pkgRoot, "files", fname);
        const dst = resolve(fontsDir, fname);
        pickedFiles.add(`${src}::${dst}`);
        return `url(/fonts/${fname})`;
      });
      sections.push(rewritten);
    }
  }
}

await Promise.all(
  [...pickedFiles].map(async (pair) => {
    const [src, dst] = pair.split("::");
    await copyFile(src, dst);
  }),
);

const banner = `/* Auto-generated by scripts/sync-assets.mjs from @fontsource packages — do not edit by hand. */\n`;
await writeFile(resolve(appDir, "public/fonts.css"), banner + sections.join("\n"), "utf8");

if (htmx) {
  const htmxSrc = resolveFromAnyNodeModules("htmx.org") + "/dist/htmx.min.js";
  await copyFile(htmxSrc, resolve(appDir, "public/htmx.min.js"));
}

console.log(`sync-assets: ${pickedFiles.size} woff2 + fonts.css (${sections.length} faces)${htmx ? " + htmx.min.js" : ""}`);

function splitFontFaceBlocks(css) {
  const blocks = [];
  const re = /(\/\*[^*]*\*\/\s*)?@font-face\s*\{[^}]*\}/g;
  let m;
  while ((m = re.exec(css))) blocks.push(m[0]);
  return blocks;
}

function blockMatchesSubsets(block, subsets) {
  const m = block.match(/\/\*\s*([^*]+?)\s*\*\//);
  if (!m) return true;
  const comment = m[1];
  for (const sub of subsets) {
    if (comment.includes(`-${sub}-`)) return true;
  }
  return false;
}

function resolveFromAnyNodeModules(pkg) {
  for (const candidate of [resolve(appDir, "node_modules", pkg), resolve(repoRoot, "node_modules", pkg)]) {
    if (existsSync(resolve(candidate, "package.json"))) return candidate;
  }
  throw new Error(`sync-assets: cannot resolve ${pkg} — install it first`);
}
