export interface Env {
  DB: D1Database;
  FEEDBACK_EMAIL: SendEmail;
  // FETCH_PROXY_* are read by the scrape script (scripts/scrape.ts) via
  // process.env, not by the worker. They live here only so the scraper
  // modules — which are still imported by the script — typecheck against
  // their existing Env signature.
  FETCH_PROXY_URL?: string;
  FETCH_PROXY_TOKEN?: string;
  DEEPL_API_KEYS?: string;
  VAPID_PUBLIC_KEY?: string;
  VAPID_PRIVATE_KEY?: string;
  VAPID_SUBJECT?: string;
}

export interface MuseumInfo {
  name: string;
  website: string | null;
  description: string | null;
  image_url: string | null;
  museumsufer?: false;
}

// Optional-rather-than-nullable on the rarely-set fields. The scrape
// generator strips null/undefined values, so absent ≡ null at runtime.
// Consumers use `?? null` / `?.` already, so the distinction never
// reaches a renderer.
export interface Museum {
  id: number;
  name: string;
  slug: string;
  museumsufer_url: string;
  website_url?: string;
  opening_hours?: string;
  description?: string;
  image_url?: string;
}

export interface Translation {
  source_hash: string;
  target_lang: string;
  source_text: string;
  translated_text: string;
}

/** Bundle of all scraped state, generated by scripts/scrape.ts. Reads
 *  go through this in-memory shape instead of D1; only `likes` stays
 *  in D1 (user-submitted, mutable). */
export interface ScrapeData {
  museums: Museum[];
  exhibitions: Exhibition[];
  events: Event[];
  translations: Translation[];
}

export interface Exhibition {
  id: number;
  museum_id: number;
  title: string;
  start_date?: string;
  end_date?: string;
  description?: string;
  image_url?: string;
  detail_url?: string;
  museum_name?: string;
  museum_slug?: string;
}

export interface ExhibitionWithLikes extends Exhibition {
  like_count: number;
  translated?: boolean;
}

export interface Event {
  id: number;
  museum_id: number;
  title: string;
  date: string;
  time?: string;
  end_time?: string;
  end_date?: string;
  description?: string;
  url?: string;
  detail_url?: string;
  image_url?: string;
  price?: string;
  category?: string;
  museum_name?: string;
  museum_slug?: string;
}

export interface EventWithLikes extends Event {
  like_count: number;
  translated?: boolean;
}
