#!/usr/bin/env bun
/**
 * Walks every theater config, calls the matching scraper module, and
 * writes the aggregated result to src/scrape-data.ts. Designed to run
 * from a GitHub Action — no D1, no SCRAPE_SECRET, no Cloudflare runtime
 * dependencies. Bun runs this file natively (no tsx).
 *
 * Output is deterministic: stable IDs (FNV-1a hashes), sorted arrays,
 * sorted object keys. Two consecutive runs on identical upstream data
 * produce byte-identical output, so the GH Action's commit-if-changed
 * step skips noisy commits.
 */
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { fnv1aInt, todayIso } from "@museumsufer/core";
import { runScraper } from "../src/scrape-runner";
import { THEATERS } from "../src/theater-config";
import type { Performance, ScrapeData, Show } from "../src/types";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const today = todayIso();

async function main() {
  const showsById = new Map<number, Show>();
  const allPerformances: Performance[] = [];
  let okCount = 0;
  let failCount = 0;

  for (const t of THEATERS) {
    process.stderr.write(`[scrape] ${t.slug.padEnd(36, " ")} `);
    try {
      const result = await runScraper(t.scraper);

      for (const s of result.shows) {
        const showId = fnv1aInt(`${t.slug}|${s.slug}`);
        if (showsById.has(showId)) continue;
        showsById.set(showId, {
          id: showId,
          theater_slug: t.slug,
          slug: s.slug,
          title: s.title,
          subtitle: s.subtitle ?? null,
          description: s.description ?? null,
          language: s.language ?? null,
          age_recommendation: s.age_recommendation ?? null,
          image_url: s.image_url ?? null,
          detail_url: s.detail_url ?? null,
          season: s.season ?? null,
        });
      }

      for (const p of result.performances) {
        if (p.date < today) continue;
        const showId = fnv1aInt(`${t.slug}|${p.show_slug}`);
        const id = fnv1aInt(`${t.slug}|${p.show_slug}|${p.date}|${p.time ?? ""}|${p.venue_room ?? ""}`);
        allPerformances.push({
          id,
          show_id: showId,
          date: p.date,
          time: p.time,
          end_time: p.end_time ?? null,
          end_date: p.end_date ?? null,
          venue_room: p.venue_room ?? null,
          provider_event_id: p.provider_event_id ?? null,
          ticket_url: p.ticket_url ?? null,
          status: p.status ?? "unknown",
          available_seats: null,
          total_seats: null,
          price_min: p.price_min ?? null,
          price_max: p.price_max ?? null,
          currency: null,
          availability_checked_at: null,
        });
      }

      process.stderr.write(`ok — ${result.shows.length} shows, ${result.performances.length} perfs\n`);
      okCount++;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      process.stderr.write(`FAIL — ${msg}\n`);
      failCount++;
    }
  }

  // Stable ordering — performances sort by date/time, shows by theater then slug.
  const shows = [...showsById.values()].sort(
    (a, b) => a.theater_slug.localeCompare(b.theater_slug) || a.slug.localeCompare(b.slug),
  );
  const performancesById = new Map<number, Performance>();
  for (const p of allPerformances) performancesById.set(p.id, p);
  const performances = [...performancesById.values()].sort(
    (a, b) =>
      a.date.localeCompare(b.date) ||
      (a.time ?? "").localeCompare(b.time ?? "") ||
      a.show_id - b.show_id ||
      (a.venue_room ?? "").localeCompare(b.venue_room ?? ""),
  );

  const data: ScrapeData = { shows, performances };
  await writeFile(resolve(root, "src/scrape-data.ts"), generateModule(data), "utf8");

  process.stderr.write(
    `\n[scrape] ${okCount}/${THEATERS.length} ok, ${failCount} failed — wrote src/scrape-data.ts (${shows.length} shows, ${performances.length} perfs)\n`,
  );

  if (failCount > 0 && okCount === 0) process.exit(1);
}

function generateModule(data: ScrapeData): string {
  // Stringify with sorted object keys so adding a field upstream doesn't
  // reorder neighbours and produce a noisy diff.
  const json = JSON.stringify(data, sortedKeysReplacer, 2);
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.
import type { ScrapeData } from "./types";

export const SCRAPE_DATA: ScrapeData = ${json};
`;
}

function sortedKeysReplacer(_key: string, value: unknown): unknown {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)));
  }
  return value;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
