#!/usr/bin/env bun
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { bundleSection } from "@museumsufer/core/bundle-writer";
import { todayIso } from "@museumsufer/core/date";
import { fnv1aInt } from "@museumsufer/core/hash";
import { type CanonicalEvent, displayNameFor, EVENTS, FRANKFURT_BBOX, inBbox } from "@museumsufer/event-hub";
import { CURATED_THEATERS, type TheaterConfig } from "../src/theater-config";
import type { AvailabilityStatus, Performance, ScrapeData, Show } from "../src/types";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const today = todayIso();

const STATUSES: ReadonlySet<AvailabilityStatus> = new Set([
  "unknown",
  "available",
  "few_left",
  "sold_out",
  "cancelled",
]);

await main();

async function main(): Promise<void> {
  const curatedBySlug = new Map(CURATED_THEATERS.map((t) => [t.slug, t]));
  const showsById = new Map<number, Show>();
  const performancesById = new Map<number, Performance>();
  const counts = new Map<string, number>();
  const orphanCoords = new Map<string, { lat: number; lon: number }>();
  const orphanUrls = new Map<string, string>();

  for (const ev of EVENTS) {
    if (ev.date < today) continue;
    if (!inBbox(ev.lat, ev.lon, FRANKFURT_BBOX)) continue;
    if (!hasStageLabel(ev)) continue;

    const showSlug = deriveShowSlug(ev);
    const showId = fnv1aInt(`${ev.source_slug}|${showSlug}`);

    if (!showsById.has(showId)) {
      showsById.set(showId, {
        id: showId,
        theater_slug: ev.source_slug,
        slug: showSlug,
        title: ev.title,
        subtitle: ev.subtitle ?? undefined,
        description: ev.description ?? undefined,
        language: ev.language ?? undefined,
        image_url: ev.image_url ?? undefined,
        detail_url: ev.detail_url ?? undefined,
      });
    }

    const perfId = fnv1aInt(`${ev.source_slug}|${showSlug}|${ev.date}|${ev.time ?? ""}|${ev.venue_room ?? ""}`);
    if (performancesById.has(perfId)) continue;
    performancesById.set(perfId, {
      id: perfId,
      show_id: showId,
      date: ev.date,
      status: pickStatus(ev),
      time: ev.time ?? undefined,
      end_time: ev.end_time ?? undefined,
      end_date: ev.end_date ?? undefined,
      venue_room: ev.venue_room ?? undefined,
      provider_event_id: ev.source_event_id,
      ticket_url: ev.ticket_url ?? undefined,
      price_min: ev.price_min ?? undefined,
      price_max: ev.price_max ?? undefined,
    });
    counts.set(ev.source_slug, (counts.get(ev.source_slug) ?? 0) + 1);
    if (!curatedBySlug.has(ev.source_slug)) {
      if (!orphanCoords.has(ev.source_slug)) orphanCoords.set(ev.source_slug, { lat: ev.lat, lon: ev.lon });
      if (!orphanUrls.has(ev.source_slug) && ev.detail_url) orphanUrls.set(ev.source_slug, originOf(ev.detail_url));
    }
  }

  const data: ScrapeData = buildScrapeData(showsById, performancesById);
  const synthesized = synthesizeTheaters(orphanCoords, orphanUrls);
  await writeFile(resolve(root, "src/scrape-data.ts"), generateModule(data), "utf8");
  await writeFile(resolve(root, "src/synthesized-theaters.ts"), generateTheatersModule(synthesized), "utf8");

  const sorted = [...counts.entries()].sort((a, b) => b[1] - a[1]);
  for (const [slug, n] of sorted) log(`  ${slug.padEnd(36, " ")} ${n} perfs`);
  log(
    `wrote ${data.shows.length} shows, ${data.performances.length} performances across ${counts.size} theaters (${synthesized.length} synthesised)`,
  );
}

function synthesizeTheaters(
  orphanCoords: Map<string, { lat: number; lon: number }>,
  orphanUrls: Map<string, string>,
): TheaterConfig[] {
  const out: TheaterConfig[] = [];
  for (const [slug, coords] of orphanCoords) {
    out.push({
      slug,
      name: displayNameFor(slug),
      address: "",
      lat: coords.lat,
      lon: coords.lon,
      website_url: orphanUrls.get(slug) ?? "",
      ticketing_provider: null,
    });
  }
  return out.sort((a, b) => a.slug.localeCompare(b.slug));
}

function originOf(url: string): string {
  try {
    return new URL(url).origin;
  } catch {
    return "";
  }
}

function generateTheatersModule(theaters: TheaterConfig[]): string {
  const entries = theaters
    .map(
      (t) =>
        `  {
    slug: ${JSON.stringify(t.slug)},
    name: ${JSON.stringify(t.name)},
    address: ${JSON.stringify(t.address)},
    lat: ${t.lat},
    lon: ${t.lon},
    website_url: ${JSON.stringify(t.website_url)},
    ticketing_provider: ${t.ticketing_provider === null ? "null" : JSON.stringify(t.ticketing_provider)},
  },`,
    )
    .join("\n");
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.
import type { TheaterConfig } from "./theater-config";

export const SYNTHESIZED_THEATERS: TheaterConfig[] = [
${entries}
];
`;
}

function hasStageLabel(ev: CanonicalEvent): boolean {
  return ev.labels.some((l) => l.label.startsWith("stage:"));
}

function pickStatus(ev: CanonicalEvent): AvailabilityStatus {
  if (ev.raw_category && STATUSES.has(ev.raw_category as AvailabilityStatus)) {
    return ev.raw_category as AvailabilityStatus;
  }
  return ev.ticket_url ? "available" : "unknown";
}

/**
 * The hub uses one source_event_id per dated performance. We need a
 * show-stable id so performances of the same production group correctly.
 * Title is the most reliable cross-performance invariant in the hub data;
 * distinct shows have distinct titles within a theater.
 */
function deriveShowSlug(ev: CanonicalEvent): string {
  return ev.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function buildScrapeData(showsById: Map<number, Show>, performancesById: Map<number, Performance>): ScrapeData {
  const shows = [...showsById.values()].sort(
    (a, b) => a.theater_slug.localeCompare(b.theater_slug) || a.slug.localeCompare(b.slug),
  );
  const performances = [...performancesById.values()].sort(
    (a, b) =>
      a.date.localeCompare(b.date) ||
      (a.time ?? "").localeCompare(b.time ?? "") ||
      a.show_id - b.show_id ||
      (a.venue_room ?? "").localeCompare(b.venue_room ?? ""),
  );
  return { shows, performances };
}

function generateModule(data: ScrapeData): string {
  return `// Auto-generated by scripts/scrape.ts — do not edit by hand.
import type { ScrapeData } from "./types";

export const SCRAPE_DATA: ScrapeData = {
${bundleSection("shows", data.shows)}
${bundleSection("performances", data.performances)}
};
`;
}

function log(msg: string): void {
  process.stderr.write(`[theaters] ${msg}\n`);
}
