// Auto-generated by scripts/scrape.ts — do not edit by hand.

/**
 * Persistent TMDb poster cache. Key: "<normalised title>|<year or '*'>".
 * Value: { id, poster } when matched; null when looked up but no match
 * (negative cache — keeps a single tombstone instead of re-querying TMDb
 * every hour for titles that don't exist there).
 */
export interface TmdbCacheEntry {
  id: number;
  poster: string | null;
}

export const TMDB_POSTER_CACHE: Record<string, TmdbCacheEntry | null> = {};
